/* Generated from per-post card metadata. Run pnpm generate:posts to update. */
export const posts = [
  {
    "title": "Installation",
    "category": "Use Blaze",
    "order": 0,
    "size": "1x1",
    "description": "Install the Python package and run your first calculation.",
    "image": "/banners/blaze_installation.webp",
    "showDescription": false,
    "showDate": false,
    "showTags": false,
    "showImage": true,
    "tags": [],
    "route": "/installation"
  },
  {
    "title": "Examples",
    "category": "Use Blaze",
    "order": 1,
    "size": "2x2",
    "description": "Explore band structures, parameter studies, and projected operators. Run the same TOML in your browser or Python.",
    "image": "/banners/blaze_examples.webp",
    "showDescription": true,
    "showDate": false,
    "showTags": false,
    "showImage": true,
    "tags": [],
    "route": "/examples"
  },
  {
    "title": "Workbench",
    "category": "Use Blaze",
    "order": 2,
    "size": "1x2",
    "description": "Build a model, configure a study, and inspect the results in your browser.",
    "image": "/banners/blaze_intro.webp",
    "showDescription": true,
    "showDate": false,
    "showTags": false,
    "showImage": true,
    "tags": [],
    "route": "/workbench-guide"
  },
  {
    "title": "API & TOML",
    "category": "Use Blaze",
    "order": 3,
    "size": "1x1",
    "description": "Configuration, coordinates, array shapes, and migration.",
    "image": "",
    "showDescription": false,
    "showDate": false,
    "showTags": false,
    "showImage": false,
    "tags": [],
    "route": "/configuration"
  },
  {
    "title": "Master’s Thesis",
    "category": "Research",
    "order": 0,
    "size": "2x2",
    "description": "Photonic moiré crystals and the two-scale theory that motivates Blaze’s operator extraction.",
    "image": "/banners/blaze_thesis.webp",
    "showDescription": true,
    "showDate": false,
    "showTags": false,
    "showImage": true,
    "tags": [],
    "route": "/thesis"
  },
  {
    "title": "Technical Report",
    "category": "Research",
    "order": 1,
    "size": "2x1",
    "description": "Numerical methods, validation, and benchmarks for two-dimensional photonic crystals.",
    "image": "/banners/blaze_intro.webp",
    "showDescription": true,
    "showDate": false,
    "showTags": false,
    "showImage": true,
    "tags": [],
    "route": "/blaze"
  },
  {
    "title": "Manuscript",
    "category": "Research",
    "order": 2,
    "size": "2x1",
    "description": "Operator construction, MPB comparisons, and mixed-precision calculations.",
    "image": "/banners/blaze_paper.webp",
    "showDescription": true,
    "showDate": false,
    "showTags": false,
    "showImage": true,
    "tags": [],
    "route": "/paper"
  }
] as const;
