/* Generated from content metadata. Run pnpm generate:content to update. */
export const posts = [
  {
    "title": "Release: Blaze2D",
    "category": "Research",
    "order": 0,
    "size": "2x1",
    "description": "The technical report: numerical methods, validation against MPB, and benchmarks.",
    "image": "/banners/blaze_intro.webp",
    "showDescription": true,
    "showDate": true,
    "date": "2026-01-08",
    "showTags": false,
    "showImage": true,
    "tags": [],
    "route": "/blaze"
  },
  {
    "title": "Installation",
    "category": "Use Blaze",
    "order": 1,
    "size": "1x1",
    "description": "Install the Python package and run your first calculation.",
    "image": "",
    "showDescription": false,
    "showDate": false,
    "showTags": false,
    "showImage": false,
    "tags": [],
    "route": "/installation"
  },
  {
    "title": "Master’s Thesis",
    "category": "Research",
    "order": 2,
    "size": "2x2",
    "description": "Photonic moiré crystals and the two-scale theory that motivates Blaze’s operator extraction.",
    "image": "/banners/blaze_thesis_moire.webp",
    "showDescription": true,
    "showDate": true,
    "date": "2026-03-27",
    "showTags": false,
    "showImage": true,
    "tags": [],
    "route": "/thesis"
  },
  {
    "title": "Workbench",
    "category": "Use Blaze",
    "order": 3,
    "size": "1x2",
    "description": "Use Blaze in your browser.",
    "image": "/banners/workbench_banner.webp",
    "showDescription": true,
    "showDate": false,
    "showTags": false,
    "showImage": true,
    "tags": [],
    "route": "/workbench-guide"
  },
  {
    "title": "API & TOML",
    "category": "Use Blaze",
    "order": 5,
    "size": "1x1",
    "description": "Configuration, coordinates, array shapes, and result conventions.",
    "image": "",
    "showDescription": false,
    "showDate": false,
    "showTags": false,
    "showImage": false,
    "tags": [],
    "route": "/configuration"
  },
  {
    "title": "Manuscript",
    "category": "Research",
    "order": 6,
    "size": "2x1",
    "description": "An unpublished, unofficial account of the architectural choices behind Blaze, validated against MPB.",
    "image": "",
    "showDescription": true,
    "showDate": false,
    "showTags": false,
    "showImage": false,
    "tags": [],
    "route": "/paper"
  }
] as const;
