// GENERATED by typst/tools/figure-export/index.mjs -- do not edit.
import type { ReactElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { writeFileSync } from 'node:fs';

import BandComparisonChart from './components/charts/BandComparisonChart';
import BandsBarChart from './components/charts/BandsBarChart';
import DeviationBoxPlotChart from './components/charts/DeviationBoxPlotChart';
import EpsilonBarChart from './components/charts/EpsilonBarChart';
import IterationBarChart from './components/charts/IterationBarChart';
import IterationDistributionChart from './components/charts/IterationDistributionChart';
import IterationTimeChart from './components/charts/IterationTimeChart';
import MemoryRatioChart from './components/charts/MemoryRatioChart';
import MemoryScalingChart from './components/charts/MemoryScalingChart';
import MemoryUsageChart from './components/charts/MemoryUsageChart';
import MultiCorePerformanceChart from './components/charts/MultiCorePerformanceChart';
import ResolutionBarChart from './components/charts/ResolutionBarChart';
import ResolutionScalingChart from './components/charts/ResolutionScalingChart';
import ResolutionSpeedupChart from './components/charts/ResolutionSpeedupChart';
import SingleCorePerformanceChart from './components/charts/SingleCorePerformanceChart';
import SpeedupScalingChart from './components/charts/SpeedupScalingChart';
import ThroughputScalingChart from './components/charts/ThroughputScalingChart';

const jobs: { out: string; element: ReactElement }[] = [
  { out: "single-core", element: <SingleCorePerformanceChart {...{"width":650,"height":420}} /> },
  { out: "multi-core", element: <MultiCorePerformanceChart {...{"width":650,"height":420}} /> },
  { out: "memory-resolution", element: <MemoryUsageChart {...{"width":1000,"height":380,"sweep":"resolution"}} /> },
  { out: "memory-bands", element: <MemoryUsageChart {...{"width":1000,"height":380,"sweep":"num_bands"}} /> },
  { out: "memory-ratio", element: <MemoryRatioChart {...{"width":1000,"height":380}} /> },
  { out: "memory-scaling", element: <MemoryScalingChart {...{"width":1000,"height":380}} /> },
  { out: "bands-tm", element: <BandComparisonChart {...{"width":550,"height":420,"polarization":"TM"}} /> },
  { out: "bands-te", element: <BandComparisonChart {...{"width":550,"height":420,"polarization":"TE"}} /> },
  { out: "deviation-tm", element: <DeviationBoxPlotChart {...{"width":400,"height":400,"polarization":"TM"}} /> },
  { out: "deviation-te", element: <DeviationBoxPlotChart {...{"width":400,"height":400,"polarization":"TE"}} /> },
  { out: "throughput-scaling", element: <ThroughputScalingChart {...{"width":1000,"height":380}} /> },
  { out: "speedup-scaling", element: <SpeedupScalingChart {...{"width":1000,"height":380}} /> },
  { out: "resolution-bar", element: <ResolutionBarChart {...{"width":1000,"height":380}} /> },
  { out: "resolution-speedup", element: <ResolutionSpeedupChart {...{"width":1000,"height":380}} /> },
  { out: "resolution-scaling", element: <ResolutionScalingChart {...{"width":1000,"height":380}} /> },
  { out: "iteration-bar", element: <IterationBarChart {...{"width":1000,"height":380}} /> },
  { out: "iteration-time", element: <IterationTimeChart {...{"width":1000,"height":380}} /> },
  { out: "iteration-distribution", element: <IterationDistributionChart {...{"width":1040,"height":380}} /> },
  { out: "epsilon-bar", element: <EpsilonBarChart {...{"width":1000,"height":380}} /> },
  { out: "bands-bar", element: <BandsBarChart {...{"width":1000,"height":380}} /> },
];

const rendered: Record<string, string> = {};
for (const job of jobs) {
  rendered[job.out] = renderToStaticMarkup(job.element);
}

writeFileSync(process.argv[2], JSON.stringify(rendered));
