#!/usr/bin/env node
// Exports the website's chart components to standalone SVGs for the Typst reports.
//
//   node index.mjs [report]        # default: blaze
//
// The charts are React components backed by @visx, and they are the single
// source of truth for how a plot looks. Rather than re-drawing them in Typst
// (which would drift from the site immediately), this renders those very
// components with react-dom/server and rewrites the result into a self-contained
// SVG. The figures are therefore identical to the page by construction.
//
// The tool lives under typst/ so all report tooling stays in one place, but it
// has to execute inside web/, where node_modules is: a staging tree is written
// to web/.figure-export/, compiled with the TypeScript already installed there,
// and run from that directory. Nothing outside the staging tree is touched.

import { execFileSync } from 'node:child_process';
import { cpSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { toStandaloneSvg, readCoverage } from './postprocess.mjs';
import { renderEpsilonGridRow } from './epsilon-grids.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const TYPST_ROOT = resolve(HERE, '..', '..');
const WEB_DIR = resolve(process.env.BLAZE_WEB_DIR ?? join(TYPST_ROOT, '..', 'web'));
const STAGE = join(WEB_DIR, '.figure-export');

const GENERATORS = {
  'epsilon-grids': (options) =>
    renderEpsilonGridRow({
      dataDir: join(WEB_DIR, 'public', 'data', 'epsilon-grids'),
      ...options,
    }),
};

function log(message) {
  process.stdout.write(`${message}\n`);
}

/**
 * Copy the chart components and their support modules into the staging tree,
 * substituting the three modules that depend on a browser.
 */
function stage(manifest) {
  rmSync(STAGE, { recursive: true, force: true });
  const src = join(STAGE, 'src');
  mkdirSync(join(src, 'components', 'charts'), { recursive: true });
  mkdirSync(join(src, 'lib'), { recursive: true });

  // Chart components, verbatim except for the swr import (see below).
  const chartsDir = join(WEB_DIR, 'components', 'charts');
  for (const file of readdirSync(chartsDir)) {
    const body = readFileSync(join(chartsDir, file), 'utf8');
    // BandComparisonChart and DeviationBoxPlotChart pull their data through
    // useSWR. Redirecting the import (rather than shadowing the package in
    // node_modules) keeps the substitution visible in the staged source.
    const patched = body.replace(/from ['"]swr['"]/g, "from '../../lib/swr-shim'");
    writeFileSync(join(src, 'components', 'charts', file), patched);
  }

  // Real type definitions; the hook shim imports its types from here.
  cpSync(join(WEB_DIR, 'lib', 'benchmark-data.ts'), join(src, 'lib', 'benchmark-data.ts'));

  // Browser-dependent modules replaced by synchronous, filesystem-backed ones.
  for (const shim of ['use-benchmarks.ts', 'paths.ts', 'data-source.ts', 'swr-shim.ts']) {
    cpSync(join(HERE, 'shims', shim), join(src, 'lib', shim));
  }

  writeFileSync(join(src, 'render.tsx'), renderEntry(manifest));
  writeFileSync(join(STAGE, 'tsconfig.json'), TSCONFIG);
  // web/package.json declares "type": "module", which would make Node treat the
  // compiled .js as ESM. The staged tree opts back into CommonJS so the tsc
  // output (and the CJS builds of @visx and react-dom/server) load directly.
  writeFileSync(join(STAGE, 'package.json'), '{ "type": "commonjs" }\n');

  return src;
}

/** Generate the entry point that renders every React-backed figure to markup. */
function renderEntry(manifest) {
  const components = [
    ...new Set(manifest.figures.filter((f) => f.component).map((f) => f.component)),
  ].sort();

  const imports = components
    .map((name) => `import ${name} from './components/charts/${name}';`)
    .join('\n');

  const jobs = manifest.figures
    .filter((f) => f.component)
    .map((f) => `  { out: ${JSON.stringify(f.out)}, element: <${f.component} {...${JSON.stringify(f.props ?? {})}} /> },`)
    .join('\n');

  return `// GENERATED by typst/tools/figure-export/index.mjs -- do not edit.
import type { ReactElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { writeFileSync } from 'node:fs';

${imports}

const jobs: { out: string; element: ReactElement }[] = [
${jobs}
];

const rendered: Record<string, string> = {};
for (const job of jobs) {
  rendered[job.out] = renderToStaticMarkup(job.element);
}

writeFileSync(process.argv[2], JSON.stringify(rendered));
`;
}

const TSCONFIG = JSON.stringify(
  {
    compilerOptions: {
      target: 'ES2022',
      lib: ['ES2022', 'DOM'],
      module: 'commonjs',
      moduleResolution: 'node',
      jsx: 'react-jsx',
      esModuleInterop: true,
      allowSyntheticDefaultImports: true,
      resolveJsonModule: true,
      skipLibCheck: true,
      strict: false,
      noEmitOnError: true,
      rootDir: 'src',
      outDir: 'build',
      types: ['node', 'react'],
    },
    include: ['src/**/*'],
  },
  null,
  2,
);

function compile() {
  execFileSync(join(WEB_DIR, 'node_modules', '.bin', 'tsc'), ['-p', join(STAGE, 'tsconfig.json')], {
    cwd: WEB_DIR,
    stdio: 'inherit',
  });
}

/** Run the compiled entry point and read back the rendered markup. */
function renderAll() {
  const out = join(STAGE, 'raw.json');
  execFileSync(process.execPath, [join(STAGE, 'build', 'render.js'), out], {
    cwd: WEB_DIR,
    stdio: 'inherit',
    env: {
      ...process.env,
      BLAZE_WEB_PUBLIC_DIR: join(WEB_DIR, 'public'),
      NODE_ENV: 'production',
    },
  });
  return JSON.parse(readFileSync(out, 'utf8'));
}

function main() {
  const name = process.argv[2] ?? 'blaze';
  const manifestPath = join(HERE, 'manifests', `${name}.mjs`);
  return import(manifestPath).then(({ default: manifest }) => {
    const figuresDir = join(TYPST_ROOT, 'reports', manifest.report, 'figures');
    mkdirSync(figuresDir, { recursive: true });

    log(`report      ${manifest.report}  (${manifest.source})`);
    log(`web         ${WEB_DIR}`);
    log(`figures     ${figuresDir}\n`);

    log('staging component tree...');
    stage(manifest);
    log('compiling with tsc...');
    compile();
    log('rendering components...\n');
    const markup = renderAll();

    // Guard rail: anything the extended face cannot draw is reported rather than
    // silently re-faced by the renderer. Run build-fonts.py if this trips.
    const coverage = readCoverage(
      join(TYPST_ROOT, 'assets', 'fonts', 'OpenAISans-Regular-Extended.ttf'),
    );

    let total = 0;
    const uncovered = new Set();
    for (const figure of manifest.figures) {
      const raw = figure.generator
        ? GENERATORS[figure.generator](figure.options ?? {})
        : markup[figure.out];

      if (!raw) throw new Error(`no markup produced for figure "${figure.out}"`);

      const { svg, width, height, panels, missingGlyphs } = toStandaloneSvg(raw, { coverage });
      missingGlyphs.forEach((glyph) => uncovered.add(glyph));
      const target = join(figuresDir, `${figure.out}.svg`);
      writeFileSync(target, `${svg}\n`);
      total += 1;

      const origin = figure.generator ? `generator:${figure.generator}` : figure.component;
      const shape = panels > 1 ? `${width}x${height}, ${panels} panels` : `${width}x${height}`;
      log(`  ${figure.out.padEnd(24)} ${String(shape).padEnd(22)} ${origin}`);
    }

    log(`\n${total} figure(s) written.`);
    if (uncovered.size > 0) {
      log('');
      log(`WARNING: no glyph in 'OpenAI Sans Extended' for: ${[...uncovered].sort().join(' ')}`);
      log('         add the range to EXTRA_RANGES in build-fonts.py and rebuild the fonts.');
    }
  });
}

main().catch((error) => {
  process.stderr.write(`${error.stack ?? error}\n`);
  process.exit(1);
});
