/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmbackend_free: (a: number, b: number) => void;
export const __wbg_wasmbulkdriver_free: (a: number, b: number) => void;
export const __wbg_wasmselectivefilter_free: (a: number, b: number) => void;
export const getSupportedSolvers: () => any;
export const getVersion: () => [number, number];
export const isSelectiveSupported: () => number;
export const validateConfig: (a: number, b: number) => [number, number, number];
export const wasmbulkdriver_dryRun: (a: number) => [number, number, number];
export const wasmbulkdriver_getJobConfigs: (a: number, b: number) => [number, number, number];
export const wasmbulkdriver_gridSize: (a: number) => any;
export const wasmbulkdriver_isEA: (a: number) => number;
export const wasmbulkdriver_isMaxwell: (a: number) => number;
export const wasmbulkdriver_jobCount: (a: number) => number;
export const wasmbulkdriver_new: (a: number, b: number) => [number, number, number];
export const wasmbulkdriver_numBands: (a: number) => number;
export const wasmbulkdriver_precision: (a: number) => [number, number];
export const wasmbulkdriver_runCollect: (a: number) => [number, number, number];
export const wasmbulkdriver_runCollectFiltered: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const wasmbulkdriver_runStreamingFiltered: (a: number, b: number, c: number, d: number, e: number, f: any) => [number, number, number];
export const wasmbulkdriver_runWithCallback: (a: number, b: any) => [number, number, number];
export const wasmbulkdriver_runWithKPointStreaming: (a: number, b: any) => [number, number, number];
export const wasmbulkdriver_solverType: (a: number) => [number, number];
export const wasmselectivefilter_bandCount: (a: number) => number;
export const wasmselectivefilter_bandIndices: (a: number) => [number, number];
export const wasmselectivefilter_clear: (a: number) => void;
export const wasmselectivefilter_isActive: (a: number) => number;
export const wasmselectivefilter_kCount: (a: number) => number;
export const wasmselectivefilter_kIndices: (a: number) => [number, number];
export const wasmselectivefilter_new: () => number;
export const wasmselectivefilter_setBandIndices: (a: number, b: number, c: number) => void;
export const wasmselectivefilter_setKIndices: (a: number, b: number, c: number) => void;
export const initPanicHook: () => void;
export const isStreamingSupported: () => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
