/**
 * The Blaze2D architecture graph: every crate, module, kernel, buffer, and
 * boundary that matters, with hand-tuned coordinates (local grid units within
 * the parent group; 1 unit = 16 world px).
 *
 * Facts (file paths, LOC, complexities, precision behavior) mirror the Rust
 * codebase as of 2026-07. When the code moves, update this file; the board is
 * only as honest as this model.
 */

import type { ArchEdge, ArchModel, ArchNode, SolveParams } from './types';

const N = (p: SolveParams) => p.nx * p.ny;
/** Subspace dimension r = |[X, P, W]| ~ 3 * bands. */
const R = (p: SolveParams) => 3 * p.bands;
/** Interleaved Complex<f32> storage. */
const C32 = 8;
/** Complex64 accumulation. */
const C64 = 16;

const nodes: ArchNode[] = [
  /* ------------------------------ interfaces ------------------------------ */
  {
    id: 'grp.interfaces',
    type: 'group',
    kind: 'interface',
    label: 'Interfaces',
    short: 'Everything that crosses the Rust boundary: config in, results out.',
    x: 10,
    y: 0,
  },
  {
    id: 'if.toml',
    parent: 'grp.interfaces',
    type: 'port',
    kind: 'interface',
    label: 'TOML config',
    short: 'The single input format: geometry, grid, k-path, sweeps, solver settings.',
    description:
      'One TOML file describes everything: `[geometry]` (lattice + atoms), `[grid]`, `[path]`, `[[sweeps]]`, `[eigensolver]`, `[solver]` precision, `[output]`. Parsed by serde into `BulkConfig` (bulk sweeps) or `JobConfig` (single runs).',
    file: 'crates/bulk-driver-core/src/config.rs',
    x: 0,
    y: 0,
    w: 9,
    h: 4,
    subpage: '/architecture/interfaces',
  },
  {
    id: 'if.cli',
    parent: 'grp.interfaces',
    type: 'module',
    kind: 'interface',
    label: 'CLI',
    short: 'blaze / blaze-bulk binaries: TOML in, CSV out.',
    description:
      'The `blaze` binary runs one band structure; `blaze-bulk` runs sweeps with `--threads` (or adaptive). Output is CSV band tables plus optional epsilon dumps and convergence diagnostics.',
    file: 'crates/cli/src/main.rs',
    loc: 695,
    x: 11,
    y: 0,
    w: 8,
    h: 4,
    subpage: '/architecture/interfaces',
  },
  {
    id: 'if.py.api',
    parent: 'grp.interfaces',
    type: 'port',
    kind: 'interface',
    label: 'PyO3 · blaze._native',
    short: 'Python surface: BulkDriver, BandResultIterator, OperatorDataExtractor.',
    description:
      'PyO3 extension module. `BulkDriver.run_streaming()` spawns a Rust worker thread and releases the GIL (`py.allow_threads`) while compute runs; Python iterates results as they arrive.',
    file: 'crates/python/src/streaming.rs',
    loc: 3369,
    badge: 'GIL released',
    parallel: 'py-worker-thread',
    x: 21,
    y: 0,
    w: 12,
    h: 4,
    subpage: '/architecture/interfaces',
  },
  {
    id: 'if.py.channel',
    parent: 'grp.interfaces',
    type: 'kernel',
    kind: 'movement',
    label: 'crossbeam channel',
    short: 'Worker thread streams results to the Python iterator, one k-row at a time.',
    description:
      'Each finished job sends a `CompactBandResult` across a crossbeam channel from the compute thread to `BandResultIterator.__next__`. This is pure data movement: the copy is the price of streaming without holding the GIL.',
    file: 'crates/python/src/streaming.rs',
    x: 35,
    y: 0,
    w: 11,
    h: 4,
  },
  {
    id: 'if.py.iter',
    parent: 'grp.interfaces',
    type: 'module',
    kind: 'interface',
    label: 'BandResultIterator',
    short: 'Lazy Python iterator over streamed results (try_next, wait, pending).',
    description:
      'Results are marshaled field-by-field into Python dicts on `__next__`. Marshaling cost is per-result, so large sweeps stay memory-flat on the Python side.',
    file: 'crates/python/src/streaming.rs',
    x: 48,
    y: 0,
    w: 12,
    h: 4,
  },
  {
    id: 'if.wasm.driver',
    parent: 'grp.interfaces',
    type: 'port',
    kind: 'interface',
    label: 'WasmBulkDriver',
    short: 'The same engine, compiled to WebAssembly, running in this site.',
    description:
      'wasm-bindgen wrapper around the identical solver core (`CpuBackend<f64>`, rustfft works on wasm32; nalgebra replaces faer for the dense step). The Examples and Workbench pages drive it from a Web Worker.',
    file: 'crates/backend-wasm/src/streaming.rs',
    loc: 1161,
    parallel: 'browser-worker',
    x: 62,
    y: 0,
    w: 11,
    h: 4,
    subpage: '/architecture/interfaces',
  },
  {
    id: 'if.wasm.cb',
    parent: 'grp.interfaces',
    type: 'kernel',
    kind: 'movement',
    label: 'JS streaming callbacks',
    short: 'Per-k-point results marshaled to JsValue and posted to the page.',
    description:
      '`runWithKPointStreaming(cb)` fires a callback per solved k-point. Rust structs are converted to JS objects at the boundary: visible, bounded, per-row data movement.',
    file: 'crates/backend-wasm/src/streaming.rs',
    x: 75,
    y: 0,
    w: 12,
    h: 4,
  },
  {
    id: 'if.csv',
    parent: 'grp.interfaces',
    type: 'port',
    kind: 'interface',
    label: 'CSV band tables',
    short: 'One band table per job: k_index, kx, ky, distance, band1..bandN.',
    file: 'crates/bulk-driver/src/output.rs',
    x: 89,
    y: 0,
    w: 10,
    h: 4,
  },
  {
    id: 'if.diag',
    parent: 'grp.interfaces',
    type: 'port',
    kind: 'interface',
    label: 'JSON diagnostics',
    short: 'Optional per-iteration convergence traces for offline analysis.',
    file: 'crates/core/src/diagnostics.rs',
    x: 101,
    y: 0,
    w: 10,
    h: 4,
  },

  /* ----------------------------- orchestration ---------------------------- */
  {
    id: 'grp.bulk',
    type: 'group',
    kind: 'control',
    label: 'Orchestration · bulk-driver',
    short: 'Sweep expansion and job-level parallelism. Parallelism lives HERE, not inside kernels.',
    file: 'crates/bulk-driver/src/driver.rs',
    loc: 5068,
    subpage: '/architecture/parallelism-and-drivers',
    x: 10,
    y: 10,
  },
  {
    id: 'bulk.parse',
    parent: 'grp.bulk',
    type: 'kernel',
    kind: 'control',
    label: 'TOML → BulkConfig',
    short: 'serde parse + validation of the entire config surface.',
    file: 'crates/bulk-driver-core/src/config.rs',
    x: 0,
    y: 0,
    w: 11,
    h: 4,
  },
  {
    id: 'bulk.expand',
    parent: 'grp.bulk',
    type: 'kernel',
    kind: 'control',
    label: 'Sweep expansion',
    short: 'Ordered [[sweeps]] become a flat Vec<ExpandedJob> (nested-loop order).',
    description:
      'Each sweep dimension (eps_bg, resolution, polarization, per-atom radius/position/epsilon) multiplies the job list. A 4-parameter sweep can expand to thousands of independent jobs.',
    file: 'crates/bulk-driver-core/src/expansion.rs',
    loc: 1066,
    x: 13,
    y: 0,
    w: 12,
    h: 4,
  },
  {
    id: 'bulk.pool',
    parent: 'grp.bulk',
    type: 'kernel',
    kind: 'control',
    label: 'rayon pool · par_iter',
    short: 'Jobs run data-parallel on a dedicated thread pool. One job = one lane.',
    description:
      '`jobs.par_iter().for_each(execute_job)` on a dedicated `ThreadPoolBuilder` pool. Jobs share the FFT plan cache and an output mutex, nothing else. This is the ONLY parallelism level: kernels below run single-threaded by design.',
    file: 'crates/bulk-driver/src/driver.rs',
    parallel: 'rayon-jobs',
    x: 27,
    y: 0,
    w: 12,
    h: 4,
    subpage: '/architecture/parallelism-and-drivers',
  },
  {
    id: 'bulk.lane1',
    parent: 'grp.bulk',
    type: 'kernel',
    kind: 'control',
    label: 'job',
    short: 'One independent solve job on its own thread.',
    x: 27,
    y: 5.5,
    w: 2.6,
    h: 2,
  },
  {
    id: 'bulk.lane2',
    parent: 'grp.bulk',
    type: 'kernel',
    kind: 'control',
    label: 'job',
    short: 'One independent solve job on its own thread.',
    x: 30.2,
    y: 5.5,
    w: 2.6,
    h: 2,
  },
  {
    id: 'bulk.lane3',
    parent: 'grp.bulk',
    type: 'kernel',
    kind: 'control',
    label: 'job',
    short: 'One independent solve job on its own thread.',
    x: 33.4,
    y: 5.5,
    w: 2.6,
    h: 2,
  },
  {
    id: 'bulk.lane4',
    parent: 'grp.bulk',
    type: 'kernel',
    kind: 'control',
    label: 'job',
    short: 'One independent solve job on its own thread.',
    x: 36.6,
    y: 5.5,
    w: 2.6,
    h: 2,
  },
  {
    id: 'bulk.adaptive',
    parent: 'grp.bulk',
    type: 'kernel',
    kind: 'control',
    label: 'AdaptiveThreadManager',
    short: 'Tunes the thread count from live job timings.',
    file: 'crates/bulk-driver/src/adaptive.rs',
    x: 41,
    y: 0,
    w: 13,
    h: 4,
  },
  {
    id: 'bulk.writer',
    parent: 'grp.bulk',
    type: 'kernel',
    kind: 'movement',
    label: 'OutputWriter',
    short: 'Mutex-guarded streaming CSV writer shared by all job threads.',
    description:
      '`Arc<Mutex<OutputWriter>>`: every finished job serializes its band table through one lock. Sync, batched, or streaming IO modes trade latency against syscall count.',
    file: 'crates/bulk-driver/src/output.rs',
    badge: 'lock',
    x: 56,
    y: 0,
    w: 11,
    h: 4,
  },

  /* ------------------------------- geometry ------------------------------- */
  {
    id: 'grp.geometry',
    type: 'group',
    kind: 'control',
    label: 'Geometry',
    short: 'Typed lattices, basis atoms, and the Brillouin-zone path.',
    subpage: '/architecture/geometry-and-dielectric',
    x: 0,
    y: 23,
  },
  {
    id: 'geo.lattice',
    parent: 'grp.geometry',
    type: 'module',
    kind: 'control',
    label: 'Lattice2D · Bravais',
    short: 'Square, rectangular, triangular, hexagonal, oblique; or explicit a1/a2.',
    file: 'crates/core/src/lattice.rs',
    x: 0,
    y: 0,
    w: 12,
    h: 4,
  },
  {
    id: 'geo.crystal',
    parent: 'grp.geometry',
    type: 'module',
    kind: 'control',
    label: 'Crystal + basis atoms',
    short: 'Fractional positions, radii, per-atom epsilon. Multi-atom bases supported.',
    file: 'crates/core/src/crystal.rs',
    x: 0,
    y: 5.5,
    w: 12,
    h: 4,
  },
  {
    id: 'geo.brillouin',
    parent: 'grp.geometry',
    type: 'module',
    kind: 'control',
    label: 'Brillouin zone · k-path',
    short: 'Path presets (Γ-X-M-Γ, Γ-M-K-Γ, ...) or explicit k-point lists.',
    file: 'crates/core/src/brillouin.rs',
    x: 0,
    y: 11,
    w: 12,
    h: 4,
  },

  /* ------------------------------ job driver ------------------------------ */
  {
    id: 'grp.driver',
    type: 'group',
    kind: 'control',
    label: 'Band-structure driver (one job)',
    short: 'The sequential k-point loop: warm starts chain each k to the previous one.',
    file: 'crates/core/src/drivers/bandstructure.rs',
    subpage: '/architecture/parallelism-and-drivers',
    x: 27,
    y: 23,
  },
  {
    id: 'drv.kloop',
    parent: 'grp.driver',
    type: 'kernel',
    kind: 'control',
    label: 'k-point loop',
    short: 'SEQUENTIAL by design: each k warm-starts from the previous solution.',
    description:
      'k-points are solved in path order. The previous eigenvectors seed the next solve (warm start), and subspace prediction transports them across k. This chaining is why one job cannot parallelize over k, and why jobs (not k-points) are the parallel unit.',
    file: 'crates/core/src/drivers/bandstructure.rs',
    parallel: 'serial-k',
    badge: 'serial',
    x: 0,
    y: 0,
    w: 11,
    h: 4,
    subpage: '/architecture/parallelism-and-drivers',
  },
  {
    id: 'drv.warm',
    parent: 'grp.driver',
    type: 'kernel',
    kind: 'movement',
    label: 'warm-start clone',
    short: 'Converged eigenvectors are cloned as the next k-point starting block.',
    file: 'crates/core/src/drivers/bandstructure.rs',
    complexity: 'O(N · bands) copy per k',
    x: 13,
    y: 0,
    w: 12,
    h: 4,
  },
  {
    id: 'drv.predict',
    parent: 'grp.driver',
    type: 'kernel',
    kind: 'compute',
    label: 'Subspace prediction',
    short: 'Polar-decomposition parallel transport aligns the gauge across k.',
    description:
      'The warm-start subspace is gauge-aligned to the previous k via polar decomposition (optionally extrapolated). Costs O(N·m² + m³) per k but cuts LOBPCG iterations sharply.',
    file: 'crates/core/src/eigensolver/subspace_prediction.rs',
    complexity: 'O(N·m² + m³) per k',
    precision: 'mixed',
    x: 27,
    y: 0,
    w: 13,
    h: 4,
  },
  {
    id: 'drv.epsclone',
    parent: 'grp.driver',
    type: 'kernel',
    kind: 'movement',
    label: 'dielectric.clone() per k',
    short: 'The O(N) epsilon arrays are cloned for every k-point.',
    file: 'crates/core/src/drivers/bandstructure.rs',
    complexity: 'O(N) copy per k',
    x: 0,
    y: 5.5,
    w: 12,
    h: 4,
  },
  {
    id: 'drv.track',
    parent: 'grp.driver',
    type: 'kernel',
    kind: 'compute',
    label: 'Band tracking',
    short: 'Polar decomposition + Hungarian matching reorder bands across k.',
    description:
      'Eigenvalues at neighboring k-points are matched by overlap so band indices stay physically continuous through crossings, instead of sorted by value.',
    file: 'crates/core/src/band_tracking.rs',
    x: 14,
    y: 5.5,
    w: 12,
    h: 4,
  },
  {
    id: 'drv.result',
    parent: 'grp.driver',
    type: 'buffer',
    kind: 'memory',
    label: 'CompactBandResult',
    short: 'The per-job result row: k-path, distances, bands[k][band].',
    file: 'crates/bulk-driver-core/src/result.rs',
    x: 28,
    y: 5.5,
    w: 12,
    h: 4,
  },

  /* -------------------------------- physics ------------------------------- */
  {
    id: 'grp.physics',
    type: 'group',
    kind: 'compute',
    label: 'Physics · crates/core',
    short: 'Dielectric construction and the matrix-free Maxwell operators.',
    subpage: '/architecture/operators',
    x: 0,
    y: 43.5,
  },
  {
    id: 'grp.dielectric',
    parent: 'grp.physics',
    type: 'group',
    kind: 'compute',
    label: 'Dielectric',
    short: 'Analytic subpixel smoothing builds ε once per job.',
    subpage: '/architecture/geometry-and-dielectric',
    x: 0,
    y: 0,
  },
  {
    id: 'diel.smooth',
    parent: 'grp.dielectric',
    type: 'kernel',
    kind: 'compute',
    label: 'Analytic subpixel smoothing',
    short: 'Exact circle-pixel intersections; MPB-style anisotropic ε̃⁻¹ tensor per boundary pixel.',
    description:
      'For every pixel crossed by an atom boundary, the exact filling fraction and interface normal give the anisotropic average ε̃⁻¹ = P⟨ε⁻¹⟩ + (1−P)⟨ε⟩⁻¹ with P = n⊗n. This is what lets coarse grids match MPB.',
    file: 'crates/core/src/dielectric.rs',
    complexity: 'O(N · atoms), once per job',
    x: 0,
    y: 0,
    w: 14,
    h: 4,
    subpage: '/architecture/geometry-and-dielectric',
  },
  {
    id: 'diel.eps',
    parent: 'grp.dielectric',
    type: 'buffer',
    kind: 'memory',
    label: 'ε(r), ε⁻¹(r), tensors',
    short: 'Real-space arrays of length N = nx·ny. No dense G-space matrix exists.',
    file: 'crates/core/src/dielectric.rs',
    complexity: 'O(N) memory',
    x: 0,
    y: 5.5,
    w: 14,
    h: 4,
  },
  {
    id: 'grp.theta',
    parent: 'grp.physics',
    type: 'group',
    kind: 'compute',
    label: 'ThetaOperator (matrix-free)',
    short: 'The Maxwell operator is never a matrix: applying it IS a handful of FFTs.',
    file: 'crates/core/src/operators/maxwell.rs',
    subpage: '/architecture/operators',
    x: 18,
    y: 0,
  },
  {
    id: 'theta.ktables',
    parent: 'grp.theta',
    type: 'buffer',
    kind: 'memory',
    label: 'k+G tables',
    short: 'Precomputed |k+G|² and components per mode, rebuilt per k-point.',
    file: 'crates/core/src/operators/maxwell.rs',
    x: 0,
    y: 0,
    w: 13,
    h: 4,
  },
  {
    id: 'theta.tm',
    parent: 'grp.theta',
    type: 'kernel',
    kind: 'compute',
    label: 'apply_tm · 2 FFTs',
    short: '−∇²: forward FFT, multiply by |k+G|², inverse FFT. Mass operator is ε.',
    file: 'crates/core/src/operators/maxwell.rs',
    complexity: 'O(N log N) / apply',
    precision: 'generic',
    x: 0,
    y: 5.5,
    w: 13,
    h: 4,
    subpage: '/architecture/operators',
  },
  {
    id: 'theta.te',
    parent: 'grp.theta',
    type: 'kernel',
    kind: 'compute',
    label: 'apply_te · 6 FFTs',
    short: '−∇·(ε⁻¹∇): gradients in G-space, tensor contraction in real space, divergence back.',
    description:
      'Six FFTs per application: potential → gradients (2 inverse), real-space ε⁻¹ tensor contraction, gradients back (2 forward), assembled divergence (1 inverse). The per-vector loop keeps grad scratch hot in L2 on purpose.',
    file: 'crates/core/src/operators/maxwell.rs',
    complexity: 'O(N log N) / apply',
    precision: 'generic',
    x: 0,
    y: 11,
    w: 13,
    h: 4,
    subpage: '/architecture/operators',
  },
  {
    id: 'theta.scratch',
    parent: 'grp.theta',
    type: 'buffer',
    kind: 'memory',
    label: 'scratch · grad_x · grad_y',
    short: 'Preallocated once, reused every apply. Zero steady-state allocation.',
    file: 'crates/core/src/operators/maxwell.rs',
    x: 0,
    y: 16.5,
    w: 13,
    h: 4,
  },
  {
    id: 'grp.precond',
    parent: 'grp.physics',
    type: 'group',
    kind: 'compute',
    label: 'Preconditioners',
    short: 'Fourier-space scaling (TM) and MPB transverse projection (TE).',
    file: 'crates/core/src/preconditioners.rs',
    x: 36,
    y: 0,
  },
  {
    id: 'pc.fourier',
    parent: 'grp.precond',
    type: 'kernel',
    kind: 'compute',
    label: 'FourierDiagonal (TM)',
    short: 'Scale by 1/(|k+G|² + shift) in G-space: 2 FFTs per apply.',
    file: 'crates/core/src/preconditioners/fourier_diagonal.rs',
    complexity: '2 FFTs / apply',
    x: 0,
    y: 0,
    w: 14,
    h: 4,
  },
  {
    id: 'pc.transverse',
    parent: 'grp.precond',
    type: 'kernel',
    kind: 'compute',
    label: 'TransverseProjection (TE)',
    short: 'MPB physics-informed preconditioner: 6 FFTs per apply.',
    file: 'crates/core/src/preconditioners/transverse_projection.rs',
    complexity: '6 FFTs / apply',
    x: 0,
    y: 5.5,
    w: 14,
    h: 4,
  },
  {
    id: 'pc.adaptive',
    parent: 'grp.precond',
    type: 'kernel',
    kind: 'control',
    label: 'Adaptive band-window shift',
    short: 'Blends a geometric shift with live eigenvalue estimates.',
    file: 'crates/core/src/preconditioners.rs',
    x: 0,
    y: 11,
    w: 14,
    h: 4,
  },

  /* -------------------------------- LOBPCG -------------------------------- */
  {
    id: 'grp.lobpcg',
    type: 'group',
    kind: 'compute',
    label: 'LOBPCG eigensolver · one iteration',
    short: 'The inner loop. Follow the ring clockwise; every GEMM crosses a precision boundary.',
    file: 'crates/core/src/eigensolver.rs',
    loc: 27697,
    subpage: '/architecture/eigensolver',
    x: 58,
    y: 39.5,
  },
  {
    id: 'lob.block',
    parent: 'grp.lobpcg',
    type: 'buffer',
    kind: 'memory',
    label: 'BlockEntry {X, B·X, A·X}',
    short: 'Three buffers per band: the block AND its mass/operator images, cached.',
    description:
      'Caching B·X and A·X alongside X means residuals need zero fresh operator applies, and the Ritz update can rebuild all three by GEMM from A·Q. Memory buys back the most expensive operation in the loop.',
    file: 'crates/core/src/eigensolver/initialization.rs',
    precision: 'generic',
    complexity: '3 · N · bands complex',
    x: 0,
    y: 0,
    w: 15,
    h: 4,
    subpage: '/architecture/eigensolver',
  },
  {
    id: 'lob.resid',
    parent: 'grp.lobpcg',
    type: 'kernel',
    kind: 'compute',
    label: 'residuals R = A·X − B·X·Λ',
    short: 'Built entirely from cached blocks: no operator applies here.',
    file: 'crates/core/src/eigensolver.rs',
    precision: 'generic',
    x: 0,
    y: 5,
    w: 15,
    h: 4,
  },
  {
    id: 'lob.lazy',
    parent: 'grp.lobpcg',
    type: 'kernel',
    kind: 'control',
    label: 'lazy residual norms',
    short: 'Norms only when logging; convergence tracks eigenvalue changes instead.',
    description:
      'Residual B-norms cost n_active mass applies. Since convergence is judged by eigenvalue movement, the norms are skipped on roughly 90% of iterations.',
    file: 'crates/core/src/eigensolver.rs',
    badge: '~90% skipped',
    x: 17,
    y: 5,
    w: 12,
    h: 3,
  },
  {
    id: 'lob.deflate',
    parent: 'grp.lobpcg',
    type: 'kernel',
    kind: 'compute',
    label: 'deflation + soft locking',
    short: 'Converged bands are projected out and frozen.',
    file: 'crates/core/src/eigensolver/deflation.rs',
    x: 0,
    y: 10,
    w: 15,
    h: 4,
  },
  {
    id: 'lob.precond',
    parent: 'grp.lobpcg',
    type: 'kernel',
    kind: 'compute',
    label: 'P = M⁻¹ R',
    short: 'Preconditioned residuals: 2 (TM) or 6 (TE) FFTs per active band.',
    file: 'crates/core/src/eigensolver.rs',
    complexity: 'O(n_active · N log N)',
    x: 0,
    y: 15,
    w: 15,
    h: 4,
  },
  {
    id: 'lob.subspace',
    parent: 'grp.lobpcg',
    type: 'kernel',
    kind: 'movement',
    label: 'assemble Z = [X, P, W]',
    short: 'The trial subspace: current block, preconditioned residuals, history.',
    file: 'crates/core/src/eigensolver.rs',
    complexity: 'r ≈ 3 · bands vectors',
    x: 0,
    y: 20,
    w: 15,
    h: 4,
  },
  {
    id: 'lob.svqb',
    parent: 'grp.lobpcg',
    type: 'kernel',
    kind: 'compute',
    label: 'SVQB B-orthonormalization',
    short: 'Gram matrix + dense eigen; near-dependent directions are rank-dropped.',
    description:
      'SVQB orthonormalizes the whole subspace in one shot (Gram + eigendecomposition), monitoring the condition number (warn at κ>1e10, critical at 1e14). Rank-dropping keeps the Rayleigh-Ritz problem well-posed.',
    file: 'crates/core/src/eigensolver/normalization.rs',
    complexity: 'O(N·r² + r³)',
    precision: 'mixed',
    badge: 'κ monitor',
    x: 17,
    y: 25,
    w: 15,
    h: 4,
    subpage: '/architecture/eigensolver',
  },
  {
    id: 'lob.aq',
    parent: 'grp.lobpcg',
    type: 'kernel',
    kind: 'compute',
    label: 'batched A·Q',
    short: 'One operator apply per subspace vector: the FFT-heavy step.',
    description:
      'A·Q is computed once per iteration and reused twice: for the projected operator Qᴴ(AQ) AND for the Ritz update A·X = AQ·Y. That reuse saves a full block of operator applies every iteration.',
    file: 'crates/core/src/eigensolver.rs',
    complexity: 'O(r · N log N)',
    precision: 'generic',
    x: 34,
    y: 25,
    w: 13,
    h: 4,
  },
  {
    id: 'lob.upcast',
    parent: 'grp.lobpcg',
    type: 'kernel',
    kind: 'movement',
    label: 'upcast → f64 (to_accum)',
    short: 'Every GEMM input is promoted from storage precision to Complex64. N×r copies.',
    description:
      'The mixed-precision contract: bulk storage may be f32, but Gram matrices, projections, and eigensolves always accumulate in f64. The price is an N×r materialized copy at every GEMM boundary; the reward is f32 bandwidth with f64 trustworthiness.',
    file: 'crates/core/src/field.rs',
    complexity: 'N · r · 16 B per GEMM',
    precision: 'mixed',
    x: 36,
    y: 20,
    w: 13,
    h: 4,
    subpage: '/architecture/precision-and-memory',
  },
  {
    id: 'lob.gemm',
    parent: 'grp.lobpcg',
    type: 'kernel',
    kind: 'compute',
    label: 'Aₛ = Qᴴ(AQ) · faer GEMM',
    short: 'Dense projection in f64. Internal GEMM parallelism is OFF by design.',
    description:
      'faer runs sequentially (`Par::Seq`): on ≤64² grids, thread synchronization made parallel GEMM 5 to 10 times SLOWER. Parallelism belongs at the job level, where there is enough work to amortize it.',
    file: 'crates/core/src/eigensolver.rs',
    complexity: 'O(N · r²)',
    precision: 'f64',
    badge: 'Par::Seq',
    x: 36,
    y: 15,
    w: 13,
    h: 4,
    subpage: '/architecture/precision-and-memory',
  },
  {
    id: 'lob.eigen',
    parent: 'grp.lobpcg',
    type: 'kernel',
    kind: 'compute',
    label: 'r×r Hermitian eigensolve',
    short: 'The Rayleigh-Ritz step: tiny, dense, always f64.',
    file: 'crates/core/src/eigensolver/dense.rs',
    complexity: 'O(r³)',
    precision: 'f64',
    x: 36,
    y: 10,
    w: 13,
    h: 4,
  },
  {
    id: 'lob.downcast',
    parent: 'grp.lobpcg',
    type: 'kernel',
    kind: 'movement',
    label: 'downcast → storage (cscalar)',
    short: 'Ritz results are written back to f32 storage precision.',
    file: 'crates/core/src/field.rs',
    precision: 'mixed',
    x: 36,
    y: 5,
    w: 13,
    h: 4,
    subpage: '/architecture/precision-and-memory',
  },
  {
    id: 'lob.ritz',
    parent: 'grp.lobpcg',
    type: 'kernel',
    kind: 'compute',
    label: 'Ritz update · 3× GEMM',
    short: 'X = Q·Y, B·X = BQ·Y, A·X = AQ·Y. Reusing A·Q avoids a block of operator applies.',
    file: 'crates/core/src/eigensolver.rs',
    complexity: 'O(N · r · bands)',
    precision: 'mixed',
    x: 36,
    y: 0,
    w: 13,
    h: 4,
  },
  {
    id: 'lob.w',
    parent: 'grp.lobpcg',
    type: 'buffer',
    kind: 'memory',
    label: 'W history',
    short: 'Previous search directions, the third block of the subspace.',
    file: 'crates/core/src/eigensolver.rs',
    precision: 'generic',
    x: 17,
    y: 10,
    w: 12,
    h: 4,
  },
  {
    id: 'lob.evals',
    parent: 'grp.lobpcg',
    type: 'buffer',
    kind: 'memory',
    label: 'eigenvalues · Vec<f64>',
    short: 'Always f64, whatever the storage precision. Variational error is O(ε²).',
    file: 'crates/core/src/eigensolver.rs',
    precision: 'f64',
    x: 17,
    y: 15,
    w: 12,
    h: 4,
  },

  /* -------------------------------- backend ------------------------------- */
  {
    id: 'grp.backend',
    type: 'group',
    kind: 'compute',
    label: 'Backend & storage',
    short: 'The FFT engine and the precision-generic storage layer.',
    subpage: '/architecture/precision-and-memory',
    x: 10,
    y: 75.5,
  },
  {
    id: 'be.trait',
    parent: 'grp.backend',
    type: 'port',
    kind: 'interface',
    label: 'SpectralBackend trait',
    short: 'FFT + BLAS-1 surface every backend implements.',
    file: 'crates/core/src/backend.rs',
    x: 0,
    y: 2.5,
    w: 12,
    h: 4,
  },
  {
    id: 'grp.cpu',
    parent: 'grp.backend',
    type: 'group',
    kind: 'compute',
    label: 'backend-cpu',
    short: 'rustfft-based CPU backend, generic over f32/f64.',
    file: 'crates/backend-cpu/src/lib.rs',
    loc: 1136,
    x: 14,
    y: 0,
  },
  {
    id: 'cpu.fft',
    parent: 'grp.cpu',
    type: 'kernel',
    kind: 'compute',
    label: 'fft_2d (rustfft)',
    short: 'Row FFTs + transposed column FFTs. The single hottest kernel.',
    file: 'crates/backend-cpu/src/lib.rs',
    complexity: 'O(N log N)',
    precision: 'generic',
    x: 0,
    y: 0,
    w: 12,
    h: 4,
    subpage: '/architecture/operators',
  },
  {
    id: 'cpu.plans',
    parent: 'grp.cpu',
    type: 'buffer',
    kind: 'memory',
    label: 'FFT plan cache',
    short: 'Arc<Mutex<FftPlanner>>: plans built once, shared across all job threads.',
    file: 'crates/backend-cpu/src/lib.rs',
    badge: 'lock',
    x: 14,
    y: 0,
    w: 12,
    h: 4,
  },
  {
    id: 'cpu.dot',
    parent: 'grp.cpu',
    type: 'kernel',
    kind: 'compute',
    label: 'dot · f64 accumulation',
    short: 'Inner products always sum in Complex64, even for f32 storage.',
    description:
      'Accumulating in f32 causes catastrophic cancellation during orthogonalization. Every summand is promoted; the accumulator never lives in storage precision.',
    file: 'crates/backend-cpu/src/lib.rs',
    precision: 'mixed',
    complexity: 'O(N), called ~r² / iter',
    x: 0,
    y: 5.5,
    w: 12,
    h: 4,
    subpage: '/architecture/precision-and-memory',
  },
  {
    id: 'cpu.axpy',
    parent: 'grp.cpu',
    type: 'kernel',
    kind: 'compute',
    label: 'axpy / scale',
    short: 'In-place BLAS-1 updates in storage precision.',
    file: 'crates/backend-cpu/src/lib.rs',
    precision: 'generic',
    x: 14,
    y: 5.5,
    w: 12,
    h: 4,
  },
  {
    id: 'cpu.transpose',
    parent: 'grp.cpu',
    type: 'kernel',
    kind: 'movement',
    label: 'transpose scratch',
    short: 'Column gather/scatter through a reused scratch buffer.',
    file: 'crates/backend-cpu/src/lib.rs',
    x: 28,
    y: 0,
    w: 12,
    h: 4,
  },
  {
    id: 'be.field',
    parent: 'grp.backend',
    type: 'buffer',
    kind: 'memory',
    label: 'Field2D<R> · Complex<R>',
    short: 'Interleaved complex, row-major (iy·nx + ix). R is f32 or f64, monomorphized.',
    file: 'crates/core/src/field.rs',
    precision: 'generic',
    x: 60,
    y: 2.5,
    w: 15,
    h: 4,
    subpage: '/architecture/precision-and-memory',
  },
  {
    id: 'be.wasm',
    parent: 'grp.backend',
    type: 'crate',
    kind: 'interface',
    label: 'backend-wasm',
    short: 'Same CpuBackend, compiled to wasm32; nalgebra replaces faer.',
    file: 'crates/backend-wasm/src/lib.rs',
    x: 78,
    y: 0,
    w: 12,
    h: 4,
  },
  {
    id: 'be.cuda',
    parent: 'grp.backend',
    type: 'crate',
    kind: 'control',
    label: 'backend-cuda',
    short: 'Placeholder. The honest note: small grids are PCIe-transfer-bound.',
    file: 'crates/backend-cuda/src/lib.rs',
    loc: 62,
    stub: true,
    x: 78,
    y: 5.5,
    w: 12,
    h: 4,
  },
];

/* --------------------------------- edges --------------------------------- */

const edges: ArchEdge[] = [
  /* config in */
  { id: 'e.toml-parse', from: 'if.toml', to: 'bulk.parse', kind: 'data', label: 'TOML text', bytes: () => 2_000 },
  { id: 'e.cli-parse', from: 'if.cli', to: 'bulk.parse', kind: 'control', label: 'config path' },
  { id: 'e.py-parse', from: 'if.py.api', to: 'bulk.parse', kind: 'control', label: 'BulkDriver(config)', route: [[38.25, 7.5], [38.25, 9.3], [14.5, 9.3], [14.5, 13.5]] },
  { id: 'e.wasm-parse', from: 'if.wasm.driver', to: 'bulk.parse', kind: 'control', label: 'new(configToml)', route: [[78.75, 7.5], [78.75, 9.7], [19, 9.7], [19, 13.5]] },

  /* orchestration */
  { id: 'e.parse-expand', from: 'bulk.parse', to: 'bulk.expand', kind: 'data', payload: 'BulkConfig', bytes: () => 4_000 },
  { id: 'e.expand-pool', from: 'bulk.expand', to: 'bulk.pool', kind: 'data', payload: 'Vec<ExpandedJob>', bytes: (p) => p.jobs * 1_000 },
  { id: 'e.adaptive-pool', from: 'bulk.adaptive', to: 'bulk.pool', kind: 'control', label: 'thread count' },
  { id: 'e.pool-lane1', from: 'bulk.pool', to: 'bulk.lane1', kind: 'control' },
  { id: 'e.pool-lane2', from: 'bulk.pool', to: 'bulk.lane2', kind: 'control' },
  { id: 'e.pool-lane3', from: 'bulk.pool', to: 'bulk.lane3', kind: 'control' },
  { id: 'e.pool-lane4', from: 'bulk.pool', to: 'bulk.lane4', kind: 'control' },
  { id: 'e.lane-driver', from: 'bulk.lane1', to: 'drv.kloop', kind: 'control', label: 'execute_job (×J, parallel)' },

  /* geometry chain */
  { id: 'e.parse-lattice', from: 'bulk.parse', to: 'geo.lattice', kind: 'data', payload: 'lattice spec', bytes: () => 200 },
  { id: 'e.lattice-crystal', from: 'geo.lattice', to: 'geo.crystal', kind: 'data', payload: 'a1, a2', payloadPrecision: 'f64' },
  { id: 'e.lattice-bz', from: 'geo.lattice', to: 'geo.brillouin', kind: 'data', payload: 'reciprocal basis', payloadPrecision: 'f64' },
  { id: 'e.crystal-smooth', from: 'geo.crystal', to: 'diel.smooth', kind: 'data', payload: 'atoms + ε values', bytes: () => 500, payloadPrecision: 'f64' },
  { id: 'e.bz-kloop', from: 'geo.brillouin', to: 'drv.kloop', kind: 'data', payload: 'k-path', bytes: (p) => p.kPoints * 16, payloadPrecision: 'f64' },

  /* dielectric */
  { id: 'e.smooth-eps', from: 'diel.smooth', to: 'diel.eps', kind: 'data', payload: 'ε arrays, O(N)', bytes: (p) => N(p) * 48, payloadPrecision: 'f64' },
  { id: 'e.eps-clone', from: 'diel.eps', to: 'drv.epsclone', kind: 'data', payload: 'clone per k', bytes: (p) => N(p) * 48, payloadPrecision: 'f64' },
  { id: 'e.clone-theta', from: 'drv.epsclone', to: 'theta.ktables', kind: 'data', payload: 'ε + Bloch k', bytes: (p) => N(p) * 48, payloadPrecision: 'f64' },

  /* driver <-> solver */
  { id: 'e.kloop-block', from: 'drv.kloop', to: 'lob.block', kind: 'control', label: 'solve at k', route: [[39.25, 28.5], [40.75, 28.5], [40.75, 38.9], [56.5, 38.9], [56.5, 45], [59.25, 45]] },
  { id: 'e.warm-block', from: 'drv.warm', to: 'lob.block', kind: 'data', payload: 'previous eigenvectors', bytes: (p) => N(p) * p.bands * C32, payloadPrecision: 'f32' },
  { id: 'e.predict-warm', from: 'drv.predict', to: 'drv.warm', kind: 'data', payload: 'transported subspace', bytes: (p) => N(p) * p.bands * C32, payloadPrecision: 'f32' },
  { id: 'e.block-warm', from: 'lob.block', to: 'drv.warm', kind: 'data', payload: 'converged X → next k', bytes: (p) => N(p) * p.bands * C32, payloadPrecision: 'f32' },
  { id: 'e.evals-track', from: 'lob.evals', to: 'drv.track', kind: 'data', payload: 'ω²(k) per band', bytes: (p) => p.bands * 8, payloadPrecision: 'f64', route: [[76.25, 60], [75.25, 60], [75.25, 37.9], [48.25, 37.9], [48.25, 36]] },
  { id: 'e.track-result', from: 'drv.track', to: 'drv.result', kind: 'data', payload: 'bands[k][band]', bytes: (p) => p.kPoints * p.bands * 8, payloadPrecision: 'f64' },

  /* LOBPCG ring (clockwise) */
  { id: 'e.block-resid', from: 'lob.block', to: 'lob.resid', kind: 'data', payload: 'X, B·X, A·X (cached)', bytes: (p) => 3 * N(p) * p.bands * C32, payloadPrecision: 'f32' },
  { id: 'e.lazy-resid', from: 'lob.lazy', to: 'lob.resid', kind: 'control', label: 'norms only when logging' },
  { id: 'e.resid-deflate', from: 'lob.resid', to: 'lob.deflate', kind: 'data', payload: 'R', bytes: (p) => N(p) * p.bands * C32, payloadPrecision: 'f32' },
  { id: 'e.deflate-precond', from: 'lob.deflate', to: 'lob.precond', kind: 'data', payload: 'R (deflated)', bytes: (p) => N(p) * p.bands * C32, payloadPrecision: 'f32' },
  { id: 'e.precond-pc', from: 'lob.precond', to: 'pc.fourier', kind: 'control', label: 'apply M⁻¹ (TM)' },
  { id: 'e.precond-pcte', from: 'lob.precond', to: 'pc.transverse', kind: 'control', label: 'apply M⁻¹ (TE)' },
  { id: 'e.adaptive-shift', from: 'pc.adaptive', to: 'pc.fourier', kind: 'control', label: 'shift from live Λ' },
  { id: 'e.precond-subspace', from: 'lob.precond', to: 'lob.subspace', kind: 'data', payload: 'P', bytes: (p) => N(p) * p.bands * C32, payloadPrecision: 'f32' },
  { id: 'e.w-subspace', from: 'lob.w', to: 'lob.subspace', kind: 'data', payload: 'W', bytes: (p) => N(p) * p.bands * C32, payloadPrecision: 'f32' },
  { id: 'e.subspace-svqb', from: 'lob.subspace', to: 'lob.svqb', kind: 'data', payload: 'Z = [X, P, W]', bytes: (p) => N(p) * R(p) * C32, payloadPrecision: 'f32' },
  { id: 'e.svqb-dot', from: 'lob.svqb', to: 'cpu.dot', kind: 'control', label: 'Gram entries ×r²', route: [[83.75, 72], [83.75, 78.5], [24.25, 78.5], [24.25, 90], [26.5, 90]] },
  { id: 'e.svqb-aq', from: 'lob.svqb', to: 'lob.aq', kind: 'data', payload: 'Q (B-orthonormal)', bytes: (p) => N(p) * R(p) * C32, payloadPrecision: 'f32' },
  { id: 'e.aq-tm', from: 'lob.aq', to: 'theta.tm', kind: 'control', label: 'apply A ×r (TM)', route: [[99.75, 72], [99.75, 74.25], [36.5, 74.25], [36.5, 58], [33.5, 58]] },
  { id: 'e.aq-te', from: 'lob.aq', to: 'theta.te', kind: 'control', label: 'apply A ×r (TE)', route: [[96, 72], [96, 74.75], [35.75, 74.75], [35.75, 63.5], [33.5, 63.5]] },
  { id: 'e.aq-upcast', from: 'lob.aq', to: 'lob.upcast', kind: 'data', payload: 'Q, AQ (storage R)', bytes: (p) => 2 * N(p) * R(p) * C32, payloadPrecision: 'f32' },
  {
    id: 'e.upcast-gemm',
    from: 'lob.upcast',
    to: 'lob.gemm',
    kind: 'data',
    payload: 'f64 matrices (materialized copies)',
    bytes: (p) => 2 * N(p) * R(p) * C64,
    precisionChange: 'upcast',
    payloadPrecision: 'f64',
  },
  { id: 'e.gemm-eigen', from: 'lob.gemm', to: 'lob.eigen', kind: 'data', payload: 'Aₛ (r×r, f64)', bytes: (p) => R(p) * R(p) * C64, payloadPrecision: 'f64' },
  { id: 'e.eigen-evals', from: 'lob.eigen', to: 'lob.evals', kind: 'data', payload: 'Ritz values (f64)', bytes: (p) => R(p) * 8, payloadPrecision: 'f64' },
  {
    id: 'e.eigen-downcast',
    from: 'lob.eigen',
    to: 'lob.downcast',
    kind: 'data',
    payload: 'Y (r×r, f64)',
    bytes: (p) => R(p) * R(p) * C64,
    payloadPrecision: 'f64',
  },
  {
    id: 'e.downcast-ritz',
    from: 'lob.downcast',
    to: 'lob.ritz',
    kind: 'data',
    payload: 'Y in storage precision',
    bytes: (p) => R(p) * R(p) * C32,
    precisionChange: 'downcast',
    payloadPrecision: 'f32',
  },
  {
    id: 'e.ritz-block',
    from: 'lob.ritz',
    to: 'lob.block',
    kind: 'data',
    payload: 'new X, B·X, A·X',
    bytes: (p) => 3 * N(p) * p.bands * C32,
    payloadPrecision: 'f32',
  },
  { id: 'e.ritz-w', from: 'lob.ritz', to: 'lob.w', kind: 'data', payload: 'new W = Q·Y₂', bytes: (p) => N(p) * p.bands * C32, payloadPrecision: 'f32' },

  /* physics -> backend */
  { id: 'e.tm-fft', from: 'theta.tm', to: 'cpu.fft', kind: 'control', label: '2 FFTs / apply' },
  { id: 'e.te-fft', from: 'theta.te', to: 'cpu.fft', kind: 'control', label: '6 FFTs / apply' },
  { id: 'e.te-scratch', from: 'theta.te', to: 'theta.scratch', kind: 'data', payload: 'reused grad buffers', bidirectional: true, bytes: (p) => 2 * N(p) * C32, payloadPrecision: 'f32' },
  { id: 'e.pcf-fft', from: 'pc.fourier', to: 'cpu.fft', kind: 'control', label: '2 FFTs / apply' },
  { id: 'e.pct-fft', from: 'pc.transverse', to: 'cpu.fft', kind: 'control', label: '6 FFTs / apply' },
  { id: 'e.fft-plans', from: 'cpu.fft', to: 'cpu.plans', kind: 'control', label: 'plan lookup' },
  { id: 'e.fft-transpose', from: 'cpu.fft', to: 'cpu.transpose', kind: 'data', payload: 'column passes', bytes: (p) => N(p) * C32, payloadPrecision: 'f32', route: [[32.5, 86.5], [32.5, 87], [53, 87], [53, 84.5], [54.5, 84.5]] },
  { id: 'e.field-fft', from: 'be.field', to: 'cpu.fft', kind: 'data', payload: 'Complex<R> buffers, in place', bytes: (p) => N(p) * C32, payloadPrecision: 'f32', route: [[78.75, 85.5], [78.75, 87.5], [35.5, 87.5], [35.5, 86.5]] },
  { id: 'e.cpu-trait', from: 'grp.cpu', to: 'be.trait', kind: 'control', label: 'implements' },
  { id: 'e.wasm-trait', from: 'be.wasm', to: 'be.trait', kind: 'control', label: 'implements', route: [[95.25, 79], [95.25, 76.75], [17.25, 76.75], [17.25, 81.5]] },
  { id: 'e.cuda-trait', from: 'be.cuda', to: 'be.trait', kind: 'control', label: 'future', route: [[89.25, 86.5], [69.5, 86.5], [69.5, 76.25], [20, 76.25], [20, 81.5]] },

  /* results out */
  { id: 'e.result-writer', from: 'drv.result', to: 'bulk.writer', kind: 'data', payload: 'band table row', bytes: (p) => p.kPoints * p.bands * 8, payloadPrecision: 'f64', route: [[68.25, 33], [71, 33], [71, 17.5]] },
  { id: 'e.writer-csv', from: 'bulk.writer', to: 'if.csv', kind: 'data', payload: 'CSV rows', bytes: (p) => p.kPoints * p.bands * 12, route: [[78.25, 15.5], [99.25, 15.5], [99.25, 5.5], [100.25, 5.5]] },
  { id: 'e.writer-diag', from: 'bulk.writer', to: 'if.diag', kind: 'data', payload: 'convergence JSON', bytes: () => 20_000, route: [[78.25, 16.5], [111.25, 16.5], [111.25, 5.5], [112.25, 5.5]] },
  { id: 'e.result-channel', from: 'drv.result', to: 'if.py.channel', kind: 'data', payload: 'CompactBandResult', bytes: (p) => p.kPoints * p.bands * 8, payloadPrecision: 'f64' },
  { id: 'e.channel-iter', from: 'if.py.channel', to: 'if.py.iter', kind: 'data', payload: 'PyDict per result', bytes: (p) => p.kPoints * p.bands * 8, payloadPrecision: 'f64' },
  { id: 'e.result-wasmcb', from: 'drv.result', to: 'if.wasm.cb', kind: 'data', payload: 'JsValue per k-point', bytes: (p) => p.bands * 8, payloadPrecision: 'f64', route: [[68.25, 34], [85.25, 34], [85.25, 5.5], [86.25, 5.5]] },
];

export const ARCH_MODEL: ArchModel = { nodes, edges };

/** The solve the board depicts by default: a small sweep so both parallelism levels show. */
export const DEFAULT_PARAMS: SolveParams = {
  nx: 32,
  ny: 32,
  bands: 8,
  kPoints: 25,
  jobs: 4,
};
