//! Envelope-approximation Hamiltonian ingredient extraction.
//!
//! This module computes the matrix elements and physical quantities needed
//! to assemble the multi-band envelope Hamiltonian for moiré photonic crystals.
//!
//! # Physical setup
//!
//! At each registry point **R** and carrier momentum **k₀**, we solve the local
//! Maxwell eigenproblem and extract:
//!
//! 1. **Eigenvalues** λₙ and **eigenvectors** uₙ
//! 2. **Velocity matrices** v^(i)_mn = ⟨uₘ|∂L₀/∂kᵢ|uₙ⟩
//! 3. **Second-derivative elements** w^(ij)_mn = ⟨uₘ|∂²L₀/∂kᵢ∂kⱼ|uₙ⟩
//! 4. **Effective mass tensor** M⁻¹_{ij,mn} (Löwdin-corrected)
//! 5. **R-derivative matrix elements** ⟨uₘ|∂L_eff/∂Rⱼ|uₙ⟩
//! 6. **Metric-derivative matrix elements** ⟨uₘ|∂B/∂Rⱼ|uₙ⟩ for Berry checks
//! 7. **Born–Huang potential** Φ_mn
//! 8. **Slow-coefficient potential** U_sc,mn (TE only)
//! 9. **Overlap matrices** S_mn(R→R') for gauge transport
//!
//! # Units
//!
//! All quantities are in **eigenvalue units**: λ = (ω/c)² in (2π/a)².
//! This is consistent with the Rust eigensolver which stores eigenvalues as
//! λ = ω² (with c = 1 and lengths in units of the lattice constant a).
//!
//! The k-vectors are in units of 2π/a (Cartesian reciprocal space).
//! Registry coordinates R are in fractional lattice coordinates.
//!
//! # Inner products
//!
//! - **TE**: standard ⟨u|v⟩ = (1/N) Σ_G u*(G) v(G)  (identity mass)
//! - **TM**: B-weighted ⟨u|v⟩_B = (1/N) Σ_r u*(r) ε(r) v(r)
//!
//! The dot product from `SpectralBackend::dot` computes u†·v without the 1/N
//! normalization, so we divide by grid_size where needed. However, since the
//! eigenvectors are already B-orthonormal (from the solver), these normalizations
//! are consistent.
//!
//! # Polarization handling
//!
//! - **TE**: L₀ is the standard eigenproblem operator. `apply_dL_dk` etc. apply
//!   derivatives of L₀ directly. Inner products are unweighted.
//!
//! - **TM**: The eigenproblem is Au = λBu (generalized). The perturbation theory
//!   for the generalized eigenproblem gives:
//!
//!   v^(i)_mn = ⟨uₘ|∂A/∂kᵢ|uₙ⟩_B / ⟨uₘ|B|uₙ⟩ - λₙ·⟨uₘ|∂B/∂kᵢ|uₙ⟩_B / ⟨uₘ|B|uₙ⟩
//!
//!   Since B doesn't depend on k (ε is independent of k), this simplifies to
//!   v^(i)_mn = ⟨uₘ|∂A/∂kᵢ|uₙ⟩ (using B-orthonormality ⟨uₘ|B|uₙ⟩ = δ_mn).
//!
//!   But the inner product ⟨·|·⟩ means the B-weighted one, and ∂A/∂kᵢ is applied
//!   by `apply_dL_dk`, so we need: v^(i)_mn = ⟨uₘ|∂A/∂kᵢ|uₙ⟩_std where the
//!   eigenvectors satisfy ⟨uₘ|B|uₙ⟩_std = δ_mn.
//!
//!   In practice, since the eigensolver stores B-orthonormal eigenvectors, we
//!   compute: v^(i)_mn = dot(uₘ, ∂A/∂kᵢ · uₙ) for both TE and TM, because
//!   ∂A/∂kᵢ is already the correctly differentiated part of the operator.
//!
//! - **TM registry derivatives**: since A is independent of registry R and
//!   B = ε(r; R), the effective perturbation entering generalized-eigenproblem
//!   perturbation theory is
//!   ∂L_eff/∂Rⱼ = -λₙ ∂B/∂Rⱼ when acting on band n.
//!
//!   We therefore keep two TM-side objects distinct:
//!   - `metric_derivative_matrices`: the Hermitian raw metric derivative
//!     ⟨uₘ|∂B/∂Rⱼ|uₙ⟩,
//!   - `r_derivative_matrices`: the effective perturbation matrix elements
//!     ⟨uₘ|∂L_eff/∂Rⱼ|uₙ⟩ = -λₙ ⟨uₘ|∂B/∂Rⱼ|uₙ⟩.
//!
//!   The Berry connection for a registry-dependent metric uses both pieces. For
//!   off-diagonal TM entries we export the gauge-fixed Hermitian quantity
//!
//!     A^(j)_{mn} = i [⟨uₘ|∂_Rⱼ uₙ⟩_B + 1/2 ⟨uₘ|∂B/∂Rⱼ|uₙ⟩],  m ≠ n,
//!
//!   which becomes
//!
//!     A^(j)_{mn} = i [⟨uₘ|∂L_eff/∂Rⱼ|uₙ⟩ / (λₙ - λₘ)
//!                   + 1/2 ⟨uₘ|∂B/∂Rⱼ|uₙ⟩].
//!
//!   We set the diagonal to zero as the default gauge choice.
//!
//!   The TM Born-Huang term is not the TE operator-side scalar correction.
//!   Instead, it is the generalized geometric potential generated by the
//!   metric variation alone,
//!
//!     Φ^(TM)_{mn} = Σ_j Σ_{ℓ∉S}
//!       ((λ_ℓ + λ_m)(λ_ℓ + λ_n) / [4(λ_m - λ_ℓ)(λ_n - λ_ℓ)])
//!       ⟨u_m|∂B/∂R_j|u_ℓ⟩ ⟨u_ℓ|∂B/∂R_j|u_n⟩,
//!
//!   while there is no separate TM U_sc term when all explicit registry
//!   dependence sits in B.

use num_complex::Complex64;

use crate::backend::{SpectralBackend, SpectralBuffer};
use crate::dielectric::DielectricDerivative;
use crate::field::{Field2D, Real, cscalar, czero};
use crate::operators::maxwell::ThetaOperator;
use crate::operators::LinearOperator;
use crate::polarization::Polarization;

// ============================================================================
// EA Ingredients — the output data structure
// ============================================================================

/// Which inner product convention is in use.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InnerProductKind {
    /// Standard unweighted ⟨u|v⟩ (TE mode).
    Standard,
    /// B-weighted ⟨u|B|v⟩ where B = ε(r) (TM mode).
    BWeighted,
}

impl InnerProductKind {
    pub fn from_polarization(pol: Polarization) -> Self {
        match pol {
            Polarization::TE => Self::Standard,
            Polarization::TM => Self::BWeighted,
        }
    }

    pub fn label(&self) -> &'static str {
        match self {
            Self::Standard => "standard",
            Self::BWeighted => "B_weighted",
        }
    }
}

/// Exact hermitized TM ingredients needed for the O(eta^2) TM Hamiltonian.
#[derive(Debug, Clone)]
pub struct OperatorDataExactTM {
    /// Hermitized local Bloch states \tilde{u}_alpha = sqrt(epsilon) u_alpha.
    /// Shape: [n_total][grid_size].
    pub hermitized_eigenvectors: Vec<Vec<Complex64>>,

    /// Exact hermitized TM velocity matrices \tilde{v}^{(i)}_{alpha beta}.
    /// Shape per direction: [n_total x n_total], row-major.
    pub velocity_matrices: [Vec<Complex64>; 2],

    /// Matrix elements of \partial_{R_i} \tilde{L}^{(0)}_{TM}.
    /// Shape per direction: [n_total x n_total], row-major.
    pub local_r_derivative_matrices: [Vec<Complex64>; 2],

    /// Matrix elements of \partial_{R_i}^2 \tilde{L}^{(0)}_{TM}.
    /// Shape per direction: [n_total x n_total], row-major.
    pub local_r_second_derivative_matrices: [Vec<Complex64>; 2],

    /// Exact first-order remainder matrix \tilde{Gamma}^{(1)}_{alpha beta}.
    /// Shape: [n_total x n_total], row-major.
    pub first_order_remainder: Vec<Complex64>,

    /// Exact direct second-order metric overlap \tilde{G}_{mn}.
    /// Shape: [n_retained x n_retained], row-major.
    pub direct_metric: Vec<Complex64>,

    /// Exact direct second-order one-derivative matrices \tilde{B}^{(i)}_{mn}.
    /// Shape per direction: [n_retained x n_retained], row-major.
    pub direct_b_matrices: [Vec<Complex64>; 2],

    /// Exact direct second-order scalar matrix \tilde{Gamma}^{(2)}_{mn}.
    /// Shape: [n_retained x n_retained], row-major.
    pub direct_gamma2: Vec<Complex64>,

    /// Exact Hermitian inverse-mass tensor built from \tilde{G} and remote-band curvature.
    /// Shape: [2][2][n_retained x n_retained], row-major in band indices.
    pub mass_tensor_inv: [[Vec<Complex64>; 2]; 2],

    /// First slow derivatives of epsilon.
    pub epsilon_r_derivatives: [Vec<f64>; 2],

    /// Second slow derivatives of epsilon.
    pub epsilon_r_second_derivatives: [Vec<f64>; 2],

    /// First slow derivatives of rho = epsilon^(-1/2).
    pub rho_r_derivatives: [Vec<f64>; 2],

    /// Second slow derivatives of rho = epsilon^(-1/2).
    pub rho_r_second_derivatives: [Vec<f64>; 2],
}

/// All EA Hamiltonian ingredients extracted at one (R, k₀) point.
///
/// Matrix elements are stored in **row-major** order: for a matrix M_{mn},
/// the element at (m, n) is at index `m * n_cols + n`.
///
/// # Units
///
/// | Quantity | Units | Description |
/// |----------|-------|-------------|
/// | eigenvalues | (2π/a)² | λ = (ω/c)², same as eigensolver output |
/// | velocity_matrices | (2π/a)² per (2π/a) = (2π/a) | ∂λ/∂k derivative units |
/// | w_matrices | (2π/a)² per (2π/a)² = dimensionless | ∂²λ/∂k² units |
/// | mass_tensor_inv | same as w_matrices | Löwdin-corrected ∂²λ/∂k² |
/// | r_derivative_matrices | (2π/a)² / fractional | effective ∂L_eff/∂R, R in frac. coords |
/// | metric_derivative_matrices | dimensionless / fractional | ∂B/∂R, zero for TE |
/// | berry_connection_matrices | 1 / fractional | gauge-fixed Hermitian A_j in retained space |
/// | born_huang | (2π/a)² | scalar potential units |
/// | slow_coefficient_potential | (2π/a)² | scalar potential units |
/// | k0 | 2π/a | Cartesian k-vector |
/// | registry | fractional | atom shift in lattice units |
#[derive(Debug, Clone)]
pub struct OperatorData {
    // -- Metadata --
    pub polarization: Polarization,
    pub inner_product: InnerProductKind,
    /// Carrier momentum k₀ in Cartesian reciprocal-space units (2π/a).
    pub k0: [f64; 2],
    /// Registry point (fractional atom shift coordinates).
    pub registry: [f64; 2],
    /// Index of the first retained band in the full eigensystem.
    pub band_lo: usize,
    pub n_retained: usize,
    pub n_remote: usize,
    pub grid_dims: [usize; 2],

    // -- Eigensystem --
    /// Eigenvalues λₙ for ALL n_total = n_retained + n_remote bands.
    /// Units: (2π/a)².
    pub eigenvalues: Vec<f64>,

    /// Eigenvectors as solver-grid field values. Shape: [n_total][grid_size].
    /// Complex64 values in the same representation as the solver output.
    pub eigenvectors: Vec<Vec<Complex64>>,

    // -- First-order: velocity matrices --
    /// v^(i)_{mn} = ⟨uₘ|∂L₀/∂kᵢ|uₙ⟩
    /// Shape per direction: [n_retained × n_total], row-major.
    /// Units: (2π/a) (eigenvalue per k-unit).
    pub velocity_matrices: [Vec<Complex64>; 2],

    // -- Second-order: raw operator 2nd derivatives --
    /// w^(ij)_{mn} = ⟨uₘ|∂²L₀/∂kᵢ∂kⱼ|uₙ⟩
    /// Shape: [n_retained × n_retained], row-major.
    /// Units: dimensionless (eigenvalue per k²-unit).
    pub w_matrices: [[Vec<Complex64>; 2]; 2],

    // -- Second-order: Löwdin-corrected mass tensor --
    /// M⁻¹_{ij,mn} including remote-band Löwdin sums.
    /// Shape: [n_retained × n_retained], row-major.
    /// Units: dimensionless.
    pub mass_tensor_inv: [[Vec<Complex64>; 2]; 2],

    // -- Registry-derivative matrix elements --
    /// ⟨uₘ|∂L₀/∂Rⱼ|uₙ⟩, shape: [n_retained × n_total], row-major.
    /// For TE this is the direct operator derivative ⟨uₘ|∂L₀/∂Rⱼ|uₙ⟩.
    /// For TM this is the effective generalized-eigenproblem perturbation
    /// ⟨uₘ|∂L_eff/∂Rⱼ|uₙ⟩ = -λₙ⟨uₘ|∂B/∂Rⱼ|uₙ⟩.
    /// Units: (2π/a)² / fractional.
    /// None if R-derivatives were not requested.
    pub r_derivative_matrices: Option<[Vec<Complex64>; 2]>,

    /// Metric-derivative matrices ⟨uₘ|∂B/∂Rⱼ|uₙ⟩, shape: [n_retained × n_total],
    /// row-major. For TE the metric is identity, so this is identically zero.
    /// Units: 1 / fractional.
    /// None if R-derivatives were not requested.
    pub metric_derivative_matrices: Option<[Vec<Complex64>; 2]>,

    /// Berry connection matrices A^(j) in the retained space, shape:
    /// [n_retained × n_retained], row-major. Off-diagonal entries follow the
    /// perturbative formulas above; diagonals are fixed to zero gauge.
    /// Units: 1 / fractional.
    /// None if R-derivatives were not requested.
    pub berry_connection_matrices: Option<[Vec<Complex64>; 2]>,

    // -- Born–Huang potential --
    /// Φ_{mn}(R), shape: [n_retained × n_retained], row-major.
    /// Units: (2π/a)².
    /// None if Born–Huang was not requested.
    pub born_huang: Option<Vec<Complex64>>,

    /// Direction-resolved Born–Huang tensor Φ^(ij)_{mn}(R), with shape
    /// [2][2][n_retained × n_retained], row-major in band indices.
    /// The scalar Born–Huang matrix above is the native-basis trace
    /// Φ^(xx) + Φ^(yy). Phase 2 can contract this tensor with the moiré metric
    /// exactly after coordinate transforms.
    pub born_huang_tensor: Option<[[Vec<Complex64>; 2]; 2]>,

    /// U_sc,mn(R), shape: [n_retained × n_retained], row-major.
    /// This is currently implemented only for TE, where it is built from the
    /// explicit registry dependence of ε⁻¹ in the second-order operator.
    /// Units: (2π/a)².
    /// None if the term was not requested or is unavailable for the active
    /// polarization.
    pub slow_coefficient_potential: Option<Vec<Complex64>>,

    /// Direction-resolved slow-coefficient tensor U_sc^(ij)_{mn}(R), with
    /// shape [2][2][n_retained × n_retained], row-major in band indices.
    /// The scalar slow-coefficient matrix above is the native-basis trace
    /// U_sc^(xx) + U_sc^(yy).
    pub slow_coefficient_tensor: Option<[[Vec<Complex64>; 2]; 2]>,

    // -- Exact TE downfolding remainder blocks --
    /// Exact TE first-order scalar block Ξ_sc^(1) from Appendix A, shape
    /// [n_retained × n_retained], row-major. This is the local scalar matrix
    /// before adding the covariantization terms that produce U_rem^(1).
    pub xi_scalar_first_order: Option<Vec<Complex64>>,

    /// Exact TE direct second-order coefficient K_i = U^† ε^{-1} Ξ_i for the
    /// retained manifold, one matrix per slow direction, each with shape
    /// [n_retained × n_retained], row-major.
    pub kappa_matrices: Option<[Vec<Complex64>; 2]>,

    /// Exact TE weighted leakage scalar Σ_i Ξ_i^† ε^{-1} Ξ_i in the retained
    /// manifold, shape [n_retained × n_retained], row-major.
    pub weighted_leakage_scalar: Option<Vec<Complex64>>,

    /// Exact TE Löwdin coupling blocks T_i = -i Q V_i U, stored as remote ×
    /// retained matrices with shape [n_remote × n_retained], row-major.
    pub lowdin_t_matrices: Option<[Vec<Complex64>; 2]>,

    /// Exact TE remote scalar block R from Appendix A, stored as a remote ×
    /// retained matrix with shape [n_remote × n_retained], row-major.
    pub lowdin_r_matrix: Option<Vec<Complex64>>,

    // -- Overlap matrix for gauge transport --
    /// S_{mn} = ⟨uₘ(R)|uₙ(R')⟩, shape: [n_retained × n_retained], row-major.
    /// None if overlap was not requested.
    pub overlap_matrix: Option<Vec<Complex64>>,

    /// Exact hermitized TM export block for the O(eta^2) TM pipeline.
    /// None for TE or when the required slow dielectric derivatives were not computed.
    pub exact_tm: Option<OperatorDataExactTM>,

    // -- Solver metadata --
    pub n_iterations: usize,
    pub converged: bool,
}

// ============================================================================
// EA Extraction Configuration
// ============================================================================

/// Configuration for what to extract.
#[derive(Debug, Clone)]
pub struct OperatorDataConfig {
    /// Index of the first retained band in the full eigensystem.
    /// Bands 0..band_lo become lower-remote, bands band_lo..band_lo+n_retained
    /// are the retained manifold, and bands band_lo+n_retained..n_total are
    /// upper-remote. Default: 0 (lowest bands retained).
    pub band_lo: usize,
    /// Number of bands to keep in the retained (active) subspace.
    pub n_retained: usize,
    /// Number of additional upper-remote bands to compute for Löwdin sums.
    pub n_remote: usize,
    /// Whether to compute the Löwdin-corrected mass tensor.
    pub compute_mass_tensor: bool,
    /// Whether to compute Born–Huang matrix elements.
    pub compute_born_huang: bool,
    /// Whether to compute the slow-coefficient potential U_sc.
    pub compute_slow_coefficient: bool,
    /// Whether to compute overlap matrix with reference eigenvectors.
    pub compute_overlap: bool,
}

impl Default for OperatorDataConfig {
    fn default() -> Self {
        Self {
            band_lo: 0,
            n_retained: 4,
            n_remote: 8,
            compute_mass_tensor: true,
            compute_born_huang: false,
            compute_slow_coefficient: false,
            compute_overlap: false,
        }
    }
}

// ============================================================================
// EA Extractor — the computation engine
// ============================================================================

/// Extracts EA Hamiltonian ingredients from a solved eigenproblem.
///
/// # Typical usage
///
/// ```ignore
/// let extractor = OperatorDataExtractor::new(&operator, &eigenvectors, &eigenvalues, config);
/// let ingredients = extractor.extract(
///     k0, registry,
///     dielectric_derivs.as_deref(),
///     reference_eigvecs.as_deref(),
///     solver_metadata,
/// );
/// ```
pub struct OperatorDataExtractor<'a, B: SpectralBackend> {
    operator: &'a mut ThetaOperator<B>,
    eigenvectors: &'a [Field2D],
    eigenvalues: &'a [f64],
    config: OperatorDataConfig,
}

impl<'a, B: SpectralBackend> OperatorDataExtractor<'a, B> {
    pub fn new(
        operator: &'a mut ThetaOperator<B>,
        eigenvectors: &'a [Field2D],
        eigenvalues: &'a [f64],
        config: OperatorDataConfig,
    ) -> Self {
        let n_total = config.band_lo + config.n_retained + config.n_remote;
        assert!(
            eigenvectors.len() >= n_total,
            "Need at least {} eigenvectors (got {})",
            n_total,
            eigenvectors.len()
        );
        assert!(
            eigenvalues.len() >= n_total,
            "Need at least {} eigenvalues (got {})",
            n_total,
            eigenvalues.len()
        );
        Self {
            operator,
            eigenvectors,
            eigenvalues,
            config,
        }
    }

    /// Run the full extraction pipeline.
    ///
    /// # Arguments
    ///
    /// * `k0` — Carrier momentum (Cartesian, 2π/a units)
    /// * `registry` — Registry point (fractional coordinates)
    /// * `diel_derivs` — Optional dielectric derivatives for ∂L₀/∂Rⱼ (2 directions)
    /// * `reference_eigvecs` — Optional eigenvectors from a neighboring R for overlap matrix
    /// * `n_iterations` — Solver iteration count (metadata)
    /// * `converged` — Whether the solver converged (metadata)
    pub fn extract(
        &mut self,
        k0: [f64; 2],
        registry: [f64; 2],
        diel_derivs: Option<&[DielectricDerivative; 2]>,
        reference_eigvecs: Option<&[Field2D]>,
        n_iterations: usize,
        converged: bool,
    ) -> OperatorData {
        let n_ret = self.config.n_retained;
        let band_lo = self.config.band_lo;
        let n_total = band_lo + n_ret + self.config.n_remote;
        let grid = self.operator.grid();
        let pol = self.operator.polarization();
        let inner_product = InnerProductKind::from_polarization(pol);

        // Collect eigenvalues and eigenvectors
        let eigenvalues = self.eigenvalues[..n_total].to_vec();
        let eigenvectors: Vec<Vec<Complex64>> = self.eigenvectors[..n_total]
            .iter()
            .map(|f| {
                f.as_slice()
                    .iter()
                    .map(|&c| Complex64::new(c.re as f64, c.im as f64))
                    .collect()
            })
            .collect();

        // -- Velocity matrices v^(i)_mn --
        let velocity_matrices = self.compute_velocity_matrices(n_ret, n_total);

        // -- Second-derivative elements w^(ij)_mn --
        let w_matrices = self.compute_w_matrices(n_ret);

        // -- Mass tensor M⁻¹_{ij,mn} --
        let mass_tensor_inv = if self.config.compute_mass_tensor {
            self.compute_mass_tensor(&velocity_matrices, &w_matrices, n_ret, n_total)
        } else {
            // Just copy w_matrices as a placeholder (no Löwdin correction)
            w_matrices.clone()
        };

        // -- R-derivative matrix elements --
        let metric_derivative_matrices = diel_derivs.map(|derivs| {
            self.compute_metric_derivative_matrices(derivs, n_ret, n_total)
        });

        let r_derivative_matrices = diel_derivs.map(|derivs| {
            self.compute_effective_r_derivative_matrices(derivs, metric_derivative_matrices.as_ref(), n_ret, n_total)
        });

        let berry_connection_matrices = match (
            r_derivative_matrices.as_ref(),
            metric_derivative_matrices.as_ref(),
        ) {
            (Some(r_mats), Some(metric_mats)) => Some(
                self.compute_berry_connection_matrices(r_mats, metric_mats, n_ret, n_total),
            ),
            _ => None,
        };

        // -- Born–Huang potential --
        let born_huang_tensor = if self.config.compute_born_huang {
            match (
                r_derivative_matrices.as_ref(),
                metric_derivative_matrices.as_ref(),
            ) {
                (Some(r_mats), Some(metric_mats)) => Some(
                    self.compute_born_huang_tensor(r_mats, metric_mats, n_ret, n_total)
                ),
                _ => None,
            }
        } else {
            None
        };

        let born_huang = born_huang_tensor
            .as_ref()
            .map(|tensor| self.trace_direction_tensor(tensor, n_ret));

        let slow_coefficient_tensor = if self.config.compute_slow_coefficient {
            match (pol, diel_derivs, r_derivative_matrices.as_ref()) {
                (Polarization::TE, Some(derivs), Some(r_mats)) => Some(
                    self.compute_slow_coefficient_tensor(derivs, r_mats, n_ret, n_total),
                ),
                _ => None,
            }
        } else {
            None
        };

        let slow_coefficient_potential = slow_coefficient_tensor
            .as_ref()
            .map(|tensor| self.trace_direction_tensor(tensor, n_ret));

        let (
            xi_scalar_first_order,
            kappa_matrices,
            weighted_leakage_scalar,
            lowdin_t_matrices,
            lowdin_r_matrix,
        ) = if pol == Polarization::TE {
            match (diel_derivs, r_derivative_matrices.as_ref()) {
                (Some(derivs), Some(r_mats)) => {
                    let exact = self.compute_exact_te_downfolding_terms(
                        derivs,
                        r_mats,
                        &velocity_matrices,
                        n_ret,
                        n_total,
                    );
                    (
                        Some(exact.xi_scalar_first_order),
                        Some(exact.kappa_matrices),
                        Some(exact.weighted_leakage_scalar),
                        Some(exact.lowdin_t_matrices),
                        Some(exact.lowdin_r_matrix),
                    )
                }
                _ => (None, None, None, None, None),
            }
        } else {
            (None, None, None, None, None)
        };

        // -- Overlap matrix --
        let overlap_matrix = if self.config.compute_overlap {
            reference_eigvecs.map(|ref_vecs| {
                self.compute_overlap_matrix(ref_vecs, n_ret, pol)
            })
        } else {
            None
        };

        let exact_tm = match (pol, diel_derivs) {
            (Polarization::TM, Some(derivs)) => Some(self.compute_exact_tm_ingredients(derivs, n_ret, n_total)),
            _ => None,
        };

        OperatorData {
            polarization: pol,
            inner_product,
            k0,
            registry,
            band_lo,
            n_retained: n_ret,
            n_remote: self.config.n_remote,
            grid_dims: [grid.nx, grid.ny],
            eigenvalues,
            eigenvectors,
            velocity_matrices,
            w_matrices,
            mass_tensor_inv,
            r_derivative_matrices,
            metric_derivative_matrices,
            berry_connection_matrices,
            born_huang,
            born_huang_tensor,
            slow_coefficient_potential,
            slow_coefficient_tensor,
            xi_scalar_first_order,
            kappa_matrices,
            weighted_leakage_scalar,
            lowdin_t_matrices,
            lowdin_r_matrix,
            overlap_matrix,
            exact_tm,
            n_iterations,
            converged,
        }
    }

    // ========================================================================
    // Velocity matrices: v^(i)_mn = ⟨uₘ|∂L₀/∂kᵢ|uₙ⟩
    // ========================================================================

    fn compute_velocity_matrices(
        &mut self,
        n_ret: usize,
        n_total: usize,
    ) -> [Vec<Complex64>; 2] {
        let band_lo = self.config.band_lo;
        let mut v = [
            vec![Complex64::new(0.0, 0.0); n_ret * n_total],
            vec![Complex64::new(0.0, 0.0); n_ret * n_total],
        ];

        let mut scratch = self.operator.alloc_field();

        for dir in 0..2 {
            for n in 0..n_total {
                // Apply ∂L₀/∂kᵢ to uₙ → scratch
                let u_n = self.eigenvector_buffer(n);
                self.operator.apply_dL_dk(&u_n, &mut scratch, dir);

                // Compute ⟨uₘ|result⟩ for m ∈ retained bands
                for m in 0..n_ret {
                    let u_m = self.eigenvector_buffer(band_lo + m);
                    let element = self.operator.backend().dot(&u_m, &scratch);
                    v[dir][m * n_total + n] = element;
                }

                self.return_buffer(u_n);
            }
        }

        v
    }

    // ========================================================================
    // Second-derivative elements: w^(ij)_mn = ⟨uₘ|∂²L₀/∂kᵢ∂kⱼ|uₙ⟩
    // ========================================================================

    fn compute_w_matrices(&mut self, n_ret: usize) -> [[Vec<Complex64>; 2]; 2] {
        let band_lo = self.config.band_lo;
        let mut w = [[
            vec![Complex64::new(0.0, 0.0); n_ret * n_ret],
            vec![Complex64::new(0.0, 0.0); n_ret * n_ret],
        ], [
            vec![Complex64::new(0.0, 0.0); n_ret * n_ret],
            vec![Complex64::new(0.0, 0.0); n_ret * n_ret],
        ]];

        let mut scratch = self.operator.alloc_field();

        for i in 0..2 {
            for j in 0..2 {
                for n in 0..n_ret {
                    let u_n = self.eigenvector_buffer(band_lo + n);
                    self.operator.apply_d2L_dk2(&u_n, &mut scratch, i, j);

                    for m in 0..n_ret {
                        let u_m = self.eigenvector_buffer(band_lo + m);
                        let element = self.operator.backend().dot(&u_m, &scratch);
                        w[i][j][m * n_ret + n] = element;
                        self.return_buffer(u_m);
                    }

                    self.return_buffer(u_n);
                }
            }
        }

        w
    }

    fn compute_w_matrices_full(&mut self, n_total: usize) -> [[Vec<Complex64>; 2]; 2] {
        let mut w = [[
            vec![Complex64::new(0.0, 0.0); n_total * n_total],
            vec![Complex64::new(0.0, 0.0); n_total * n_total],
        ], [
            vec![Complex64::new(0.0, 0.0); n_total * n_total],
            vec![Complex64::new(0.0, 0.0); n_total * n_total],
        ]];

        let mut scratch = self.operator.alloc_field();

        for i in 0..2 {
            for j in 0..2 {
                for n in 0..n_total {
                    let u_n = self.eigenvector_buffer(n);
                    self.operator.apply_d2L_dk2(&u_n, &mut scratch, i, j);

                    for m in 0..n_total {
                        let u_m = self.eigenvector_buffer(m);
                        let element = self.operator.backend().dot(&u_m, &scratch);
                        w[i][j][m * n_total + n] = element;
                        self.return_buffer(u_m);
                    }

                    self.return_buffer(u_n);
                }
            }
        }

        w
    }

    // ========================================================================
    // Löwdin-corrected mass tensor
    // ========================================================================
    //
    // M⁻¹_{ij,mn} = w^(ij)_{mn} + Σ_{ℓ∉S} [ v^(i)_{mℓ} v^(j)_{ℓn} / (λₙ - λℓ)
    //                                        + v^(j)_{mℓ} v^(i)_{ℓn} / (λₘ - λℓ) ]
    //
    // where S is the retained set {1..n_ret} and ℓ runs over remote bands.

    fn compute_mass_tensor(
        &self,
        velocity: &[Vec<Complex64>; 2],
        w: &[[Vec<Complex64>; 2]; 2],
        n_ret: usize,
        n_total: usize,
    ) -> [[Vec<Complex64>; 2]; 2] {
        let band_lo = self.config.band_lo;
        let eigenvalues = &self.eigenvalues[..n_total];
        let mut m_inv = [[
            vec![Complex64::new(0.0, 0.0); n_ret * n_ret],
            vec![Complex64::new(0.0, 0.0); n_ret * n_ret],
        ], [
            vec![Complex64::new(0.0, 0.0); n_ret * n_ret],
            vec![Complex64::new(0.0, 0.0); n_ret * n_ret],
        ]];

        for i in 0..2 {
            for j in 0..2 {
                for m in 0..n_ret {
                    for n in 0..n_ret {
                        let idx = m * n_ret + n;

                        // Start with the direct second-derivative element
                        let mut val = w[i][j][idx];

                        // Add Löwdin sum over remote bands ℓ ∉ retained
                        for ell in (0..band_lo).chain((band_lo + n_ret)..n_total) {
                            let lambda_n = eigenvalues[band_lo + n];
                            let lambda_m = eigenvalues[band_lo + m];
                            let lambda_ell = eigenvalues[ell];

                            // v^(i)_{m,ℓ} and v^(j)_{ℓ,n}
                            // velocity layout: v[dir][m * n_total + n], shape [n_ret × n_total]
                            let v_i_m_ell = velocity[i][m * n_total + ell];

                            // We need ⟨uℓ|∂L/∂kⱼ|uₙ⟩ for ℓ ≥ n_ret. Since ∂L₀/∂kᵢ
                            // is Hermitian (L₀(k) is a Hermitian family):
                            //   ⟨uℓ|∂L₀/∂kᵢ|uₙ⟩ = ⟨uₙ|∂L₀/∂kᵢ|uℓ⟩*
                            let v_j_ell_n = velocity[j][n * n_total + ell].conj();

                            let v_j_m_ell = velocity[j][m * n_total + ell];
                            let v_i_ell_n = velocity[i][n * n_total + ell].conj();

                            // Löwdin contribution:
                            //   v^(i)_{m,ℓ} v^(j)_{ℓ,n} / (λₙ - λℓ)
                            // + v^(j)_{m,ℓ} v^(i)_{ℓ,n} / (λₘ - λℓ)

                            let denom_n = lambda_n - lambda_ell;
                            let denom_m = lambda_m - lambda_ell;

                            // Guard against near-degeneracy (shouldn't happen for remote bands)
                            if denom_n.abs() > 1e-15 {
                                val += v_i_m_ell * v_j_ell_n / denom_n;
                            }
                            if denom_m.abs() > 1e-15 {
                                val += v_j_m_ell * v_i_ell_n / denom_m;
                            }
                        }

                        m_inv[i][j][idx] = val;
                    }
                }
            }
        }

        m_inv
    }

    // ========================================================================
    // Metric-derivative matrix elements: ⟨uₘ|∂B/∂Rⱼ|uₙ⟩
    // ========================================================================

    fn compute_metric_derivative_matrices(
        &mut self,
        diel_derivs: &[DielectricDerivative; 2],
        n_ret: usize,
        n_total: usize,
    ) -> [Vec<Complex64>; 2] {
        let band_lo = self.config.band_lo;
        let mut metric_mats = [
            vec![Complex64::new(0.0, 0.0); n_ret * n_total],
            vec![Complex64::new(0.0, 0.0); n_ret * n_total],
        ];

        if self.operator.polarization() != Polarization::TM {
            return metric_mats;
        }

        let mut scratch = self.operator.alloc_field();

        for dir in 0..2 {
            for n in 0..n_total {
                let u_n = self.eigenvector_buffer(n);
                self.operator.apply_dL_dR(&u_n, &mut scratch, &diel_derivs[dir]);

                for m in 0..n_ret {
                    let u_m = self.eigenvector_buffer(band_lo + m);
                    let element = self.operator.backend().dot(&u_m, &scratch);
                    metric_mats[dir][m * n_total + n] = element;
                    self.return_buffer(u_m);
                }

                self.return_buffer(u_n);
            }
        }

        metric_mats
    }

    fn compute_effective_r_derivative_matrices(
        &mut self,
        diel_derivs: &[DielectricDerivative; 2],
        metric_mats: Option<&[Vec<Complex64>; 2]>,
        n_ret: usize,
        n_total: usize,
    ) -> [Vec<Complex64>; 2] {
        let band_lo = self.config.band_lo;
        if self.operator.polarization() != Polarization::TM {
            let mut r_mats = [
                vec![Complex64::new(0.0, 0.0); n_ret * n_total],
                vec![Complex64::new(0.0, 0.0); n_ret * n_total],
            ];
            let mut scratch = self.operator.alloc_field();

            for dir in 0..2 {
                for n in 0..n_total {
                    let u_n = self.eigenvector_buffer(n);
                    self.operator.apply_dL_dR(&u_n, &mut scratch, &diel_derivs[dir]);

                    for m in 0..n_ret {
                        let u_m = self.eigenvector_buffer(band_lo + m);
                        let element = self.operator.backend().dot(&u_m, &scratch);
                        r_mats[dir][m * n_total + n] = element;
                        self.return_buffer(u_m);
                    }

                    self.return_buffer(u_n);
                }
            }

            return r_mats;
        }

        let metric_mats = metric_mats.expect("TM effective R-derivatives require metric derivative matrices");

        let mut r_mats = [
            vec![Complex64::new(0.0, 0.0); n_ret * n_total],
            vec![Complex64::new(0.0, 0.0); n_ret * n_total],
        ];

        for dir in 0..2 {
            for m in 0..n_ret {
                for n in 0..n_total {
                    r_mats[dir][m * n_total + n] = -self.eigenvalues[n] * metric_mats[dir][m * n_total + n];
                }
            }
        }

        r_mats
    }

    fn compute_berry_connection_matrices(
        &self,
        r_mats: &[Vec<Complex64>; 2],
        metric_mats: &[Vec<Complex64>; 2],
        n_ret: usize,
        n_total: usize,
    ) -> [Vec<Complex64>; 2] {
        let band_lo = self.config.band_lo;
        let mut berry = [
            vec![Complex64::new(0.0, 0.0); n_ret * n_ret],
            vec![Complex64::new(0.0, 0.0); n_ret * n_ret],
        ];

        for dir in 0..2 {
            for m in 0..n_ret {
                for n in 0..n_ret {
                    if m == n {
                        continue;
                    }

                    let denom = self.eigenvalues[band_lo + n] - self.eigenvalues[band_lo + m];
                    if denom.abs() <= 1e-15 {
                        continue;
                    }

                    let mut value = Complex64::new(0.0, 1.0) * r_mats[dir][m * n_total + (band_lo + n)] / denom;
                    if self.operator.polarization() == Polarization::TM {
                        value += Complex64::new(0.0, 0.5) * metric_mats[dir][m * n_total + (band_lo + n)];
                    }

                    berry[dir][m * n_ret + n] = value;
                }
            }
        }

        berry
    }

    // ========================================================================
    // Born–Huang potential
    // ========================================================================
    //
    // TE:
    //   Φ_{mn}(R) = Σ_j Σ_{ℓ∉S} ⟨∂Rⱼ uₘ|(1-P)|∂Rⱼ uₙ⟩
    //             = Σ_j Σ_{ℓ∉S}
    //               [⟨uℓ|∂L₀/∂Rⱼ|uₘ⟩* ⟨uℓ|∂L₀/∂Rⱼ|uₙ⟩] / [(λₘ - λℓ)(λₙ - λℓ)]
    //
    // TM:
    //   With A independent of R and all registry dependence in B, the
    //   generalized Born-Huang term is the metric-compatible geometric
    //   potential
    //
    //   Φ^(TM)_{mn} = Σ_j Σ_{ℓ∉S}
    //     ((λ_ℓ + λ_m)(λ_ℓ + λ_n) / [4(λ_m - λ_ℓ)(λ_n - λ_ℓ)])
    //     ⟨u_m|∂B/∂R_j|u_ℓ⟩ ⟨u_ℓ|∂B/∂R_j|u_n⟩.

    fn compute_born_huang_tensor(
        &self,
        r_mats: &[Vec<Complex64>; 2],
        metric_mats: &[Vec<Complex64>; 2],
        n_ret: usize,
        n_total: usize,
    ) -> [[Vec<Complex64>; 2]; 2] {
        let band_lo = self.config.band_lo;
        let eigenvalues = &self.eigenvalues[..n_total];
        let mut phi = self.empty_direction_tensor(n_ret);

        if self.operator.polarization() == Polarization::TM {
            for i in 0..2 {
                for j in 0..2 {
                    for m in 0..n_ret {
                        for n in 0..n_ret {
                            let idx = m * n_ret + n;
                            let lambda_m = eigenvalues[band_lo + m];
                            let lambda_n = eigenvalues[band_lo + n];

                        for ell in (0..band_lo).chain((band_lo + n_ret)..n_total) {
                            let lambda_ell = eigenvalues[ell];
                            let denom_m = lambda_m - lambda_ell;
                            let denom_n = lambda_n - lambda_ell;

                            if denom_m.abs() <= 1e-15 || denom_n.abs() <= 1e-15 {
                                continue;
                            }

                            let prefactor =
                                ((lambda_ell + lambda_m) * (lambda_ell + lambda_n))
                                    / (4.0 * denom_m * denom_n);
                                let b_i_m_ell = metric_mats[i][m * n_total + ell];
                                let b_j_ell_n = metric_mats[j][n * n_total + ell].conj();
                                phi[i][j][idx] += prefactor * b_i_m_ell * b_j_ell_n;
                            }
                        }
                    }
                }
            }

            self.hermitize_direction_tensor(&mut phi, n_ret);
            return phi;
        }

        for i in 0..2 {
            for j in 0..2 {
                for m in 0..n_ret {
                    for n in 0..n_ret {
                        let idx = m * n_ret + n;
                        let lambda_m = eigenvalues[band_lo + m];
                        let lambda_n = eigenvalues[band_lo + n];

                    for ell in (0..band_lo).chain((band_lo + n_ret)..n_total) {
                        let lambda_ell = eigenvalues[ell];
                        let denom_m = lambda_m - lambda_ell;
                        let denom_n = lambda_n - lambda_ell;

                        if denom_m.abs() > 1e-15 && denom_n.abs() > 1e-15 {
                                let r_i_ell_m = r_mats[i][m * n_total + ell].conj();
                                let r_j_ell_n = r_mats[j][n * n_total + ell].conj();
                                phi[i][j][idx] += r_i_ell_m.conj() * r_j_ell_n / (denom_m * denom_n);
                            }
                        }
                    }
                }
            }
        }

        self.hermitize_direction_tensor(&mut phi, n_ret);
        phi
    }

    // ========================================================================
    // Slow-coefficient potential
    // ========================================================================
    //
    // TE-only implementation.
    //
    // We reconstruct the registry-derivative states |∂_{R_j} u_n⟩ within the
    // computed local band window using first-order perturbation theory,
    //
    //   ⟨u_ell|∂_{R_j} u_n⟩ = ⟨u_ell|∂L/∂R_j|u_n⟩ / (λ_n - λ_ell),  ell != n,
    //
    // with the diagonal fixed to zero gauge. The slow-coefficient potential is
    // then assembled from the explicit ε⁻¹(R) registry dependence using the
    // TE operator derivative and a Hermitian symmetrization:
    //
    //   U_sc^(j) = -1/2 [ ⟨u_m| (∂L/∂R_j) |∂_{R_j}u_n⟩
    //                   + ⟨∂_{R_j}u_m| (∂L/∂R_j) |u_n⟩ ].
    //
    // This keeps U_sc distinct from the Born–Huang projector leakage term.
    // For TM there is no separate operator-side slow-coefficient term in the
    // current generalized-eigenproblem convention; the second-order geometric
    // correction is entirely carried by the generalized Born-Huang matrix.

    fn compute_slow_coefficient_tensor(
        &mut self,
        diel_derivs: &[DielectricDerivative; 2],
        r_mats: &[Vec<Complex64>; 2],
        n_ret: usize,
        n_total: usize,
    ) -> [[Vec<Complex64>; 2]; 2] {
        let band_lo = self.config.band_lo;
        let mut usc = self.empty_direction_tensor(n_ret);

        let derivative_states: [Vec<B::Buffer>; 2] = std::array::from_fn(|direction| {
            (0..n_ret)
                .map(|band| self.reconstruct_registry_basis_derivative(r_mats, direction, band, band_lo, n_total))
                .collect()
        });

        let mut d_l_on_u: [Vec<B::Buffer>; 2] = std::array::from_fn(|_| Vec::with_capacity(n_ret));
        for dir in 0..2 {
            for band in 0..n_ret {
                let u_band = self.eigenvector_buffer(band_lo + band);
                let mut scratch_u = self.operator.alloc_field();
                self.zero_buffer(&mut scratch_u);
                self.operator.apply_dL_dR(&u_band, &mut scratch_u, &diel_derivs[dir]);
                d_l_on_u[dir].push(scratch_u);
                self.return_buffer(u_band);
            }
        }

        let mut d_l_on_du: [[Vec<B::Buffer>; 2]; 2] =
            std::array::from_fn(|_| std::array::from_fn(|_| Vec::with_capacity(n_ret)));
        for left_dir in 0..2 {
            for deriv_dir in 0..2 {
                for band in 0..n_ret {
                    let mut scratch_du = self.operator.alloc_field();
                    self.zero_buffer(&mut scratch_du);
                    self.operator.apply_dL_dR(
                        &derivative_states[deriv_dir][band],
                        &mut scratch_du,
                        &diel_derivs[left_dir],
                    );
                    d_l_on_du[left_dir][deriv_dir].push(scratch_du);
                }
            }
        }

        for left_dir in 0..2 {
            for right_dir in 0..2 {
                for m in 0..n_ret {
                    let u_m = self.eigenvector_buffer(band_lo + m);
                    for n in 0..n_ret {
                        let idx = m * n_ret + n;
                        let lhs = self.operator.backend().dot(&u_m, &d_l_on_du[left_dir][right_dir][n]);
                        let rhs = self.operator.backend().dot(&derivative_states[left_dir][m], &d_l_on_u[right_dir][n]);
                        usc[left_dir][right_dir][idx] -= 0.5 * (lhs + rhs);
                    }
                    self.return_buffer(u_m);
                }
            }
        }

        for buffers in derivative_states {
            for buf in buffers {
                self.return_buffer(buf);
            }
        }
        for buffers in d_l_on_u {
            for buf in buffers {
                self.return_buffer(buf);
            }
        }
        for row in d_l_on_du {
            for buffers in row {
                for buf in buffers {
                    self.return_buffer(buf);
                }
            }
        }

        self.hermitize_direction_tensor(&mut usc, n_ret);
        usc
    }

    fn compute_exact_te_downfolding_terms(
        &mut self,
        diel_derivs: &[DielectricDerivative; 2],
        r_mats: &[Vec<Complex64>; 2],
        velocity: &[Vec<Complex64>; 2],
        n_ret: usize,
        n_total: usize,
    ) -> ExactTeDownfoldingTerms {
        let band_lo = self.config.band_lo;
        let n_remote = n_total - n_ret;
        let w_full = self.compute_w_matrices_full(n_total);

        // Helper: map absolute band index to remote row index.
        // Lower remote 0..band_lo → rows 0..band_lo
        // Upper remote (band_lo+n_ret)..n_total → rows band_lo..(n_total-n_ret)
        let remote_row = |ell: usize| -> usize {
            if ell < band_lo { ell } else { ell - n_ret }
        };

        let xi_states: [Vec<B::Buffer>; 2] = std::array::from_fn(|direction| {
            (0..n_ret)
                .map(|band| self.reconstruct_registry_leakage_state(r_mats, direction, band, n_ret, n_total))
                .collect()
        });

        let mut xi_scalar_first_order = vec![Complex64::new(0.0, 0.0); n_ret * n_ret];
        let mut kappa_matrices = [
            vec![Complex64::new(0.0, 0.0); n_ret * n_ret],
            vec![Complex64::new(0.0, 0.0); n_ret * n_ret],
        ];
        let mut weighted_leakage_scalar = vec![Complex64::new(0.0, 0.0); n_ret * n_ret];
        let mut lowdin_t_matrices = [
            vec![Complex64::new(0.0, 0.0); n_remote * n_ret],
            vec![Complex64::new(0.0, 0.0); n_remote * n_ret],
        ];
        let mut lowdin_r_matrix = vec![Complex64::new(0.0, 0.0); n_remote * n_ret];

        let mut scratch_vxi = self.operator.alloc_field();
        let mut scratch_coeff = self.operator.alloc_field();

        for dir in 0..2 {
            for ell in (0..band_lo).chain((band_lo + n_ret)..n_total) {
                let rr = remote_row(ell);
                for n in 0..n_ret {
                    lowdin_t_matrices[dir][rr * n_ret + n] =
                        -Complex64::new(0.0, 1.0) * velocity[dir][n * n_total + ell].conj();
                }
            }

            let g_full = &w_full[dir][dir];

            for n in 0..n_ret {
                self.operator.apply_dL_dk(&xi_states[dir][n], &mut scratch_vxi, dir);

                let u_n = self.eigenvector_buffer(band_lo + n);
                self.operator.apply_dinv_eps_gradient_component_te(
                    &u_n,
                    &mut scratch_coeff,
                    &diel_derivs[dir],
                    dir,
                );
                self.return_buffer(u_n);

                for m in 0..n_ret {
                    let u_m = self.eigenvector_buffer(band_lo + m);
                    let retained_vxi = self.operator.backend().dot(&u_m, &scratch_vxi);
                    let retained_coeff = self.operator.backend().dot(&u_m, &scratch_coeff);
                    xi_scalar_first_order[m * n_ret + n] -=
                        Complex64::new(0.0, 1.0) * retained_vxi + retained_coeff;
                    self.return_buffer(u_m);
                }

                for ell in (0..band_lo).chain((band_lo + n_ret)..n_total) {
                    let rr = remote_row(ell);
                    let u_ell = self.eigenvector_buffer(ell);
                    let remote_vxi = self.operator.backend().dot(&u_ell, &scratch_vxi);
                    let remote_coeff = self.operator.backend().dot(&u_ell, &scratch_coeff);
                    lowdin_r_matrix[rr * n_ret + n] -=
                        Complex64::new(0.0, 1.0) * remote_vxi + remote_coeff;
                    self.return_buffer(u_ell);
                }

                for m in 0..n_ret {
                    let mut kappa = Complex64::new(0.0, 0.0);
                    for ell in (0..band_lo).chain((band_lo + n_ret)..n_total) {
                        let coeff = self.registry_leakage_coefficient(r_mats, dir, n, ell, n_total);
                        if coeff.norm() <= 1e-15 {
                            continue;
                        }
                        kappa += 0.5 * g_full[(band_lo + m) * n_total + ell] * coeff;
                    }
                    kappa_matrices[dir][m * n_ret + n] = kappa;
                }
            }

            for m in 0..n_ret {
                for n in 0..n_ret {
                    let idx = m * n_ret + n;
                    let mut weighted = Complex64::new(0.0, 0.0);
                    for ell in (0..band_lo).chain((band_lo + n_ret)..n_total) {
                        let coeff_m = self.registry_leakage_coefficient(r_mats, dir, m, ell, n_total);
                        if coeff_m.norm() <= 1e-15 {
                            continue;
                        }
                        for ell_p in (0..band_lo).chain((band_lo + n_ret)..n_total) {
                            let coeff_n = self.registry_leakage_coefficient(r_mats, dir, n, ell_p, n_total);
                            if coeff_n.norm() <= 1e-15 {
                                continue;
                            }
                            weighted += 0.5 * coeff_m.conj() * g_full[ell * n_total + ell_p] * coeff_n;
                        }
                    }
                    weighted_leakage_scalar[idx] += weighted;
                }
            }
        }

        self.hermitize_matrix(&mut weighted_leakage_scalar, n_ret);

        ExactTeDownfoldingTerms {
            xi_scalar_first_order,
            kappa_matrices,
            weighted_leakage_scalar,
            lowdin_t_matrices,
            lowdin_r_matrix,
        }
    }

    fn compute_exact_tm_ingredients(
        &mut self,
        diel_derivs: &[DielectricDerivative; 2],
        n_ret: usize,
        n_total: usize,
    ) -> OperatorDataExactTM {
        let hermitized_buffers: Vec<B::Buffer> = (0..n_total)
            .map(|band| self.hermitized_eigenvector_buffer(band))
            .collect();

        let hermitized_eigenvectors: Vec<Vec<Complex64>> = hermitized_buffers
            .iter()
            .map(|buf| self.buffer_to_complex_vec(buf))
            .collect();

        let velocity_matrices = self.compute_tm_exact_velocity_matrices(n_total);
        let local_r_derivative_matrices =
            self.compute_tm_local_r_derivative_matrices(&hermitized_buffers, diel_derivs, n_total);
        let local_r_second_derivative_matrices = self.compute_tm_local_r_second_derivative_matrices(
            &hermitized_buffers,
            diel_derivs,
            n_total,
        );

        let first_derivative_coeffs =
            self.compute_tm_first_derivative_coefficients(&local_r_derivative_matrices, n_total);
        let first_derivative_states = self.build_tm_first_derivative_states(
            &hermitized_buffers,
            &first_derivative_coeffs,
            n_total,
        );
        let second_derivative_states = self.build_tm_second_derivative_states(
            &hermitized_buffers,
            &local_r_derivative_matrices,
            &local_r_second_derivative_matrices,
            &first_derivative_coeffs,
            n_ret,
            n_total,
        );

        let first_order_remainder = self.compute_tm_exact_first_order_remainder(
            &hermitized_buffers,
            &first_derivative_states,
            diel_derivs,
            n_total,
        );
        let direct_metric = self.compute_tm_exact_direct_metric(&hermitized_buffers, n_ret);
        let direct_b_matrices = self.compute_tm_exact_direct_b_matrices(
            &hermitized_buffers,
            &first_derivative_states,
            diel_derivs,
            n_ret,
        );
        let direct_gamma2 = self.compute_tm_exact_direct_gamma2(
            &hermitized_buffers,
            &first_derivative_states,
            &second_derivative_states,
            diel_derivs,
            n_ret,
        );
        let mass_tensor_inv =
            self.compute_tm_exact_mass_tensor(&velocity_matrices, &direct_metric, n_ret, n_total);

        for state_vec in first_derivative_states {
            for buf in state_vec {
                self.return_buffer(buf);
            }
        }
        for state_vec in second_derivative_states {
            for buf in state_vec {
                self.return_buffer(buf);
            }
        }
        for buf in hermitized_buffers {
            self.return_buffer(buf);
        }

        OperatorDataExactTM {
            hermitized_eigenvectors,
            velocity_matrices,
            local_r_derivative_matrices,
            local_r_second_derivative_matrices,
            first_order_remainder,
            direct_metric,
            direct_b_matrices,
            direct_gamma2,
            mass_tensor_inv,
            epsilon_r_derivatives: [diel_derivs[0].d_eps.clone(), diel_derivs[1].d_eps.clone()],
            epsilon_r_second_derivatives: [
                diel_derivs[0].d2_eps.clone(),
                diel_derivs[1].d2_eps.clone(),
            ],
            rho_r_derivatives: [diel_derivs[0].d_rho.clone(), diel_derivs[1].d_rho.clone()],
            rho_r_second_derivatives: [
                diel_derivs[0].d2_rho.clone(),
                diel_derivs[1].d2_rho.clone(),
            ],
        }
    }

    fn compute_tm_exact_velocity_matrices(
        &mut self,
        n_total: usize,
    ) -> [Vec<Complex64>; 2] {
        let mut velocity = [
            vec![Complex64::new(0.0, 0.0); n_total * n_total],
            vec![Complex64::new(0.0, 0.0); n_total * n_total],
        ];
        let mut scratch = self.operator.alloc_field();

        for dir in 0..2 {
            for beta in 0..n_total {
                let u_beta = self.eigenvector_buffer(beta);
                self.operator.apply_dL_dk(&u_beta, &mut scratch, dir);
                for alpha in 0..n_total {
                    let u_alpha = self.eigenvector_buffer(alpha);
                    velocity[dir][alpha * n_total + beta] =
                        self.operator.backend().dot(&u_alpha, &scratch);
                    self.return_buffer(u_alpha);
                }
                self.return_buffer(u_beta);
            }
        }

        velocity
    }

    fn compute_tm_local_r_derivative_matrices(
        &mut self,
        hermitized_buffers: &[B::Buffer],
        diel_derivs: &[DielectricDerivative; 2],
        n_total: usize,
    ) -> [Vec<Complex64>; 2] {
        let mut matrices = [
            vec![Complex64::new(0.0, 0.0); n_total * n_total],
            vec![Complex64::new(0.0, 0.0); n_total * n_total],
        ];
        let mut scratch = self.operator.alloc_field();

        for dir in 0..2 {
            for beta in 0..n_total {
                self.operator.apply_tm_hermitized_local_r_derivative(
                    &hermitized_buffers[beta],
                    &mut scratch,
                    &diel_derivs[dir].d_rho,
                );
                for alpha in 0..n_total {
                    matrices[dir][alpha * n_total + beta] =
                        self.operator.backend().dot(&hermitized_buffers[alpha], &scratch);
                }
            }
        }

        matrices
    }

    fn compute_tm_local_r_second_derivative_matrices(
        &mut self,
        hermitized_buffers: &[B::Buffer],
        diel_derivs: &[DielectricDerivative; 2],
        n_total: usize,
    ) -> [Vec<Complex64>; 2] {
        let mut matrices = [
            vec![Complex64::new(0.0, 0.0); n_total * n_total],
            vec![Complex64::new(0.0, 0.0); n_total * n_total],
        ];
        let mut scratch = self.operator.alloc_field();

        for dir in 0..2 {
            for beta in 0..n_total {
                self.operator.apply_tm_hermitized_local_r_second_derivative(
                    &hermitized_buffers[beta],
                    &mut scratch,
                    &diel_derivs[dir].d_rho,
                    &diel_derivs[dir].d2_rho,
                );
                for alpha in 0..n_total {
                    matrices[dir][alpha * n_total + beta] =
                        self.operator.backend().dot(&hermitized_buffers[alpha], &scratch);
                }
            }
        }

        matrices
    }

    fn compute_tm_first_derivative_coefficients(
        &self,
        local_r_derivative_matrices: &[Vec<Complex64>; 2],
        n_total: usize,
    ) -> [Vec<Complex64>; 2] {
        let mut coeffs = [
            vec![Complex64::new(0.0, 0.0); n_total * n_total],
            vec![Complex64::new(0.0, 0.0); n_total * n_total],
        ];

        for dir in 0..2 {
            for beta in 0..n_total {
                let lambda_beta = self.eigenvalues[beta];
                for ell in 0..n_total {
                    if ell == beta {
                        continue;
                    }
                    let denom = lambda_beta - self.eigenvalues[ell];
                    if denom.abs() <= 1e-15 {
                        continue;
                    }
                    coeffs[dir][beta * n_total + ell] =
                        local_r_derivative_matrices[dir][ell * n_total + beta] / denom;
                }
            }
        }

        coeffs
    }

    fn build_tm_first_derivative_states(
        &self,
        hermitized_buffers: &[B::Buffer],
        first_derivative_coeffs: &[Vec<Complex64>; 2],
        n_total: usize,
    ) -> [Vec<B::Buffer>; 2] {
        std::array::from_fn(|dir| {
            (0..n_total)
                .map(|beta| {
                    let mut derivative = self.operator.alloc_field();
                    self.zero_buffer(&mut derivative);
                    for ell in 0..n_total {
                        if ell == beta {
                            continue;
                        }
                        let coeff = first_derivative_coeffs[dir][beta * n_total + ell];
                        if coeff.norm() <= 1e-15 {
                            continue;
                        }
                        self.operator
                            .backend()
                            .axpy(coeff, &hermitized_buffers[ell], &mut derivative);
                    }
                    derivative
                })
                .collect()
        })
    }

    fn build_tm_second_derivative_states(
        &self,
        hermitized_buffers: &[B::Buffer],
        local_r_derivative_matrices: &[Vec<Complex64>; 2],
        local_r_second_derivative_matrices: &[Vec<Complex64>; 2],
        first_derivative_coeffs: &[Vec<Complex64>; 2],
        n_ret: usize,
        n_total: usize,
    ) -> [Vec<B::Buffer>; 2] {
        let band_lo = self.config.band_lo;
        std::array::from_fn(|dir| {
            (0..n_ret)
                .map(|local_beta| {
                    let beta = band_lo + local_beta;
                    let lambda_beta = self.eigenvalues[beta];
                    let lambda_prime = local_r_derivative_matrices[dir][beta * n_total + beta];
                    let mut second = self.operator.alloc_field();
                    self.zero_buffer(&mut second);

                    let mut diagonal_coeff = 0.0f64;
                    for p in 0..n_total {
                        if p == beta {
                            continue;
                        }
                        diagonal_coeff += first_derivative_coeffs[dir][beta * n_total + p].norm_sqr();
                    }
                    self.operator.backend().axpy(
                        Complex64::new(-diagonal_coeff, 0.0),
                        &hermitized_buffers[beta],
                        &mut second,
                    );

                    for ell in 0..n_total {
                        if ell == beta {
                            continue;
                        }
                        let denom = lambda_beta - self.eigenvalues[ell];
                        if denom.abs() <= 1e-15 {
                            continue;
                        }

                        let mut numerator = local_r_second_derivative_matrices[dir][ell * n_total + beta]
                            - 2.0 * lambda_prime * first_derivative_coeffs[dir][beta * n_total + ell];

                        for p in 0..n_total {
                            if p == beta {
                                continue;
                            }
                            numerator += 2.0
                                * local_r_derivative_matrices[dir][ell * n_total + p]
                                * first_derivative_coeffs[dir][beta * n_total + p];
                        }

                        let coeff = numerator / denom;
                        if coeff.norm() <= 1e-15 {
                            continue;
                        }
                        self.operator
                            .backend()
                            .axpy(coeff, &hermitized_buffers[ell], &mut second);
                    }

                    second
                })
                .collect()
        })
    }

    fn compute_tm_exact_first_order_remainder(
        &mut self,
        hermitized_buffers: &[B::Buffer],
        first_derivative_states: &[Vec<B::Buffer>; 2],
        diel_derivs: &[DielectricDerivative; 2],
        n_total: usize,
    ) -> Vec<Complex64> {
        let mut gamma = vec![Complex64::new(0.0, 0.0); n_total * n_total];
        let mut scratch_v = self.operator.alloc_field();
        let mut scratch_rho = self.operator.alloc_field();
        let imag = Complex64::new(0.0, 1.0);

        for dir in 0..2 {
            for beta in 0..n_total {
                self.operator.apply_tm_hermitized_fast_derivative(
                    &first_derivative_states[dir][beta],
                    &mut scratch_v,
                    dir,
                );

                self.copy_buffer(&mut scratch_rho, &hermitized_buffers[beta]);
                self.scale_buffer_by_real_field(&mut scratch_rho, &diel_derivs[dir].d_rho);
                let mut scratch_rho_out = self.operator.alloc_field();
                self.operator
                    .apply_tm_rho_covariant_gradient(&scratch_rho, &mut scratch_rho_out, dir);

                for alpha in 0..n_total {
                    let idx = alpha * n_total + beta;
                    let v_term = self.operator.backend().dot(&hermitized_buffers[alpha], &scratch_v);
                    let rho_term = self.operator.backend().dot(&hermitized_buffers[alpha], &scratch_rho_out);
                    gamma[idx] -= imag * v_term + 2.0 * rho_term;
                }

                self.return_buffer(scratch_rho_out);
            }
        }

        gamma
    }

    fn compute_tm_exact_direct_metric(
        &mut self,
        hermitized_buffers: &[B::Buffer],
        n_ret: usize,
    ) -> Vec<Complex64> {
        let band_lo = self.config.band_lo;
        let inv_eps = self.operator.dielectric().inv_eps().to_vec();
        let mut metric = vec![Complex64::new(0.0, 0.0); n_ret * n_ret];
        let mut scratch = self.operator.alloc_field();

        for n in 0..n_ret {
            self.copy_buffer(&mut scratch, &hermitized_buffers[band_lo + n]);
            self.scale_buffer_by_real_field(&mut scratch, &inv_eps);
            for m in 0..n_ret {
                metric[m * n_ret + n] = self.operator.backend().dot(&hermitized_buffers[band_lo + m], &scratch);
            }
        }

        self.hermitize_matrix(&mut metric, n_ret);
        metric
    }

    fn compute_tm_exact_direct_b_matrices(
        &mut self,
        hermitized_buffers: &[B::Buffer],
        first_derivative_states: &[Vec<B::Buffer>; 2],
        diel_derivs: &[DielectricDerivative; 2],
        n_ret: usize,
    ) -> [Vec<Complex64>; 2] {
        let band_lo = self.config.band_lo;
        let rho: Vec<f64> = self.operator.dielectric().eps().iter().map(|&eps| eps.powf(-0.5)).collect();
        let mut b_mats = [
            vec![Complex64::new(0.0, 0.0); n_ret * n_ret],
            vec![Complex64::new(0.0, 0.0); n_ret * n_ret],
        ];
        let mut scratch = self.operator.alloc_field();

        for dir in 0..2 {
            for n in 0..n_ret {
                self.copy_buffer(&mut scratch, &first_derivative_states[dir][band_lo + n]);
                self.scale_buffer_by_real_field(&mut scratch, &rho);

                let mut material = self.operator.alloc_field();
                self.copy_buffer(&mut material, &hermitized_buffers[band_lo + n]);
                self.scale_buffer_by_real_field(&mut material, &diel_derivs[dir].d_rho);
                self.operator.backend().axpy(Complex64::new(1.0, 0.0), &material, &mut scratch);
                self.scale_buffer_by_real_field(&mut scratch, &rho);
                self.scale_buffer(&mut scratch, 2.0);

                for m in 0..n_ret {
                    b_mats[dir][m * n_ret + n] = self.operator.backend().dot(&hermitized_buffers[band_lo + m], &scratch);
                }

                self.return_buffer(material);
            }
            self.hermitize_matrix(&mut b_mats[dir], n_ret);
        }

        b_mats
    }

    fn compute_tm_exact_direct_gamma2(
        &mut self,
        hermitized_buffers: &[B::Buffer],
        first_derivative_states: &[Vec<B::Buffer>; 2],
        second_derivative_states: &[Vec<B::Buffer>; 2],
        diel_derivs: &[DielectricDerivative; 2],
        n_ret: usize,
    ) -> Vec<Complex64> {
        let band_lo = self.config.band_lo;
        let rho: Vec<f64> = self.operator.dielectric().eps().iter().map(|&eps| eps.powf(-0.5)).collect();
        let mut gamma2 = vec![Complex64::new(0.0, 0.0); n_ret * n_ret];
        let mut scratch = self.operator.alloc_field();

        for dir in 0..2 {
            for n in 0..n_ret {
                // second_derivative_states is [n_ret]-sized, local index n is fine
                self.copy_buffer(&mut scratch, &second_derivative_states[dir][n]);
                self.scale_buffer_by_real_field(&mut scratch, &rho);

                let mut first = self.operator.alloc_field();
                self.copy_buffer(&mut first, &first_derivative_states[dir][band_lo + n]);
                self.scale_buffer_by_real_field(&mut first, &diel_derivs[dir].d_rho);
                self.scale_buffer(&mut first, 2.0);
                self.operator.backend().axpy(Complex64::new(1.0, 0.0), &first, &mut scratch);

                let mut zeroth = self.operator.alloc_field();
                self.copy_buffer(&mut zeroth, &hermitized_buffers[band_lo + n]);
                self.scale_buffer_by_real_field(&mut zeroth, &diel_derivs[dir].d2_rho);
                self.operator.backend().axpy(Complex64::new(1.0, 0.0), &zeroth, &mut scratch);

                self.scale_buffer_by_real_field(&mut scratch, &rho);

                for m in 0..n_ret {
                    gamma2[m * n_ret + n] -= self.operator.backend().dot(&hermitized_buffers[band_lo + m], &scratch);
                }

                self.return_buffer(first);
                self.return_buffer(zeroth);
            }
        }

        self.hermitize_matrix(&mut gamma2, n_ret);
        gamma2
    }

    fn compute_tm_exact_mass_tensor(
        &self,
        velocity: &[Vec<Complex64>; 2],
        direct_metric: &[Complex64],
        n_ret: usize,
        n_total: usize,
    ) -> [[Vec<Complex64>; 2]; 2] {
        let band_lo = self.config.band_lo;
        let mut mass = [[
            vec![Complex64::new(0.0, 0.0); n_ret * n_ret],
            vec![Complex64::new(0.0, 0.0); n_ret * n_ret],
        ], [
            vec![Complex64::new(0.0, 0.0); n_ret * n_ret],
            vec![Complex64::new(0.0, 0.0); n_ret * n_ret],
        ]];

        for i in 0..2 {
            for j in 0..2 {
                for m in 0..n_ret {
                    for n in 0..n_ret {
                        let idx = m * n_ret + n;
                        let mut val = if i == j {
                            2.0 * direct_metric[idx]
                        } else {
                            Complex64::new(0.0, 0.0)
                        };

                        // Velocity is [n_total × n_total], use absolute indices
                        let abs_m = band_lo + m;
                        let abs_n = band_lo + n;
                        for ell in (0..band_lo).chain((band_lo + n_ret)..n_total) {
                            let lambda_n = self.eigenvalues[abs_n];
                            let lambda_m = self.eigenvalues[abs_m];
                            let lambda_ell = self.eigenvalues[ell];
                            let denom_n = lambda_n - lambda_ell;
                            let denom_m = lambda_m - lambda_ell;

                            if denom_n.abs() > 1e-15 {
                                val += velocity[i][abs_m * n_total + ell] * velocity[j][ell * n_total + abs_n] / denom_n;
                            }
                            if denom_m.abs() > 1e-15 {
                                val += velocity[j][abs_m * n_total + ell] * velocity[i][ell * n_total + abs_n] / denom_m;
                            }
                        }

                        mass[i][j][idx] = val;
                    }
                }
            }
        }

        self.hermitize_direction_tensor(&mut mass, n_ret);
        mass
    }

    // ========================================================================
    // Overlap matrix: S_mn = ⟨uₘ(R)|uₙ(R')⟩
    // ========================================================================

    fn compute_overlap_matrix(
        &mut self,
        reference_eigvecs: &[Field2D],
        n_ret: usize,
        _pol: Polarization,
    ) -> Vec<Complex64> {
        let band_lo = self.config.band_lo;
        let mut overlap = vec![Complex64::new(0.0, 0.0); n_ret * n_ret];
        let n_ref = reference_eigvecs.len().min(n_ret);

        for n in 0..n_ref {
            // For TE: ⟨uₘ|uₙ'⟩ = dot(uₘ, uₙ')
            // For TM: ⟨uₘ|B|uₙ'⟩ = dot(uₘ, B·uₙ')
            // apply_mass handles both cases (identity for TE, ε multiply for TM)
            let u_n_ref = self.field_to_buffer(&reference_eigvecs[n]);
            let mut mass_u_n = self.operator.alloc_field();
            self.operator.apply_mass(&u_n_ref, &mut mass_u_n);

            for m in 0..n_ret {
                let u_m = self.eigenvector_buffer(band_lo + m);
                overlap[m * n_ret + n] = self.operator.backend().dot(&u_m, &mass_u_n);
                self.return_buffer(u_m);
            }

            self.return_buffer(u_n_ref);
        }

        overlap
    }

    // ========================================================================
    // Helper: convert Field2D eigenvectors into backend buffers
    // ========================================================================

    /// Create a backend buffer from an eigenvector (f64 → storage precision).
    fn eigenvector_buffer(&self, index: usize) -> B::Buffer {
        let field = &self.eigenvectors[index];
        self.field_to_buffer(field)
    }

    /// Convert a Field2D (f64) into a backend buffer at storage precision.
    fn field_to_buffer(&self, field: &Field2D) -> B::Buffer {
        let mut buf = self.operator.alloc_field();
        let dst = buf.as_mut_slice();
        for (d, &s) in dst.iter_mut().zip(field.as_slice().iter()) {
            *d = cscalar::<B::Real>(s.re, s.im);
        }
        buf
    }

    fn copy_buffer(&self, dst: &mut B::Buffer, src: &B::Buffer) {
        dst.as_mut_slice().copy_from_slice(src.as_slice());
    }

    fn hermitized_eigenvector_buffer(&self, index: usize) -> B::Buffer {
        let mut buf = self.eigenvector_buffer(index);
        let sqrt_eps: Vec<f64> = self
            .operator
            .dielectric()
            .eps()
            .iter()
            .map(|&eps| eps.sqrt())
            .collect();
        self.scale_buffer_by_real_field(&mut buf, &sqrt_eps);
        buf
    }

    fn buffer_to_complex_vec(&self, buffer: &B::Buffer) -> Vec<Complex64> {
        buffer
            .as_slice()
            .iter()
            .map(|&c| Complex64::new(c.re.to_accum(), c.im.to_accum()))
            .collect()
    }

    fn scale_buffer_by_real_field(&self, buffer: &mut B::Buffer, values: &[f64]) {
        for (value, &scale) in buffer.as_mut_slice().iter_mut().zip(values.iter()) {
            *value *= <B::Real as Real>::from_accum(scale);
        }
    }

    fn scale_buffer(&self, buffer: &mut B::Buffer, scale: f64) {
        let s = <B::Real as Real>::from_accum(scale);
        for value in buffer.as_mut_slice().iter_mut() {
            *value *= s;
        }
    }

    fn reconstruct_registry_basis_derivative(
        &self,
        r_mats: &[Vec<Complex64>; 2],
        direction: usize,
        band: usize,
        band_lo: usize,
        n_total: usize,
    ) -> B::Buffer {
        let mut derivative = self.operator.alloc_field();
        self.zero_buffer(&mut derivative);

        let abs_band = band_lo + band;
        let lambda_n = self.eigenvalues[abs_band];
        for ell in 0..n_total {
            if ell == abs_band {
                continue;
            }

            let denom = lambda_n - self.eigenvalues[ell];
            if denom.abs() <= 1e-15 {
                continue;
            }

            let coeff = r_mats[direction][band * n_total + ell].conj() / denom;
            if coeff.norm() <= 1e-15 {
                continue;
            }

            let u_ell = self.eigenvector_buffer(ell);
            self.operator.backend().axpy(coeff, &u_ell, &mut derivative);
            self.return_buffer(u_ell);
        }

        derivative
    }

    fn reconstruct_registry_leakage_state(
        &self,
        r_mats: &[Vec<Complex64>; 2],
        direction: usize,
        band: usize,
        n_ret: usize,
        n_total: usize,
    ) -> B::Buffer {
        let band_lo = self.config.band_lo;
        let mut derivative = self.operator.alloc_field();
        self.zero_buffer(&mut derivative);

        for ell in (0..band_lo).chain((band_lo + n_ret)..n_total) {
            let coeff = self.registry_leakage_coefficient(r_mats, direction, band, ell, n_total);
            if coeff.norm() <= 1e-15 {
                continue;
            }
            let u_ell = self.eigenvector_buffer(ell);
            self.operator.backend().axpy(coeff, &u_ell, &mut derivative);
            self.return_buffer(u_ell);
        }

        derivative
    }

    fn registry_leakage_coefficient(
        &self,
        r_mats: &[Vec<Complex64>; 2],
        direction: usize,
        band: usize,
        ell: usize,
        n_total: usize,
    ) -> Complex64 {
        let abs_band = self.config.band_lo + band;
        if ell == abs_band {
            return Complex64::new(0.0, 0.0);
        }

        let denom = self.eigenvalues[abs_band] - self.eigenvalues[ell];
        if denom.abs() <= 1e-15 {
            return Complex64::new(0.0, 0.0);
        }

        r_mats[direction][band * n_total + ell].conj() / denom
    }

    fn hermitize_matrix(&self, matrix: &mut [Complex64], n: usize) {
        for i in 0..n {
            let diag_idx = i * n + i;
            matrix[diag_idx] = Complex64::new(matrix[diag_idx].re, 0.0);

            for j in (i + 1)..n {
                let ij = i * n + j;
                let ji = j * n + i;
                let avg = 0.5 * (matrix[ij] + matrix[ji].conj());
                matrix[ij] = avg;
                matrix[ji] = avg.conj();
            }
        }
    }

    fn hermitize_direction_tensor(&self, tensor: &mut [[Vec<Complex64>; 2]; 2], n: usize) {
        self.hermitize_matrix(&mut tensor[0][0], n);
        self.hermitize_matrix(&mut tensor[1][1], n);

        for i in 0..n {
            for j in 0..n {
                let ij = i * n + j;
                let ji = j * n + i;
                let avg = 0.5 * (tensor[0][1][ij] + tensor[1][0][ji].conj());
                tensor[0][1][ij] = avg;
                tensor[1][0][ji] = avg.conj();
            }
        }
    }

    fn empty_direction_tensor(&self, n_ret: usize) -> [[Vec<Complex64>; 2]; 2] {
        std::array::from_fn(|_| {
            std::array::from_fn(|_| vec![Complex64::new(0.0, 0.0); n_ret * n_ret])
        })
    }

    fn trace_direction_tensor(
        &self,
        tensor: &[[Vec<Complex64>; 2]; 2],
        n_ret: usize,
    ) -> Vec<Complex64> {
        let mut traced = vec![Complex64::new(0.0, 0.0); n_ret * n_ret];
        for idx in 0..(n_ret * n_ret) {
            traced[idx] = tensor[0][0][idx] + tensor[1][1][idx];
        }
        self.hermitize_matrix(&mut traced, n_ret);
        traced
    }

    fn zero_buffer(&self, buffer: &mut B::Buffer) {
        let z = czero::<B::Real>();
        for value in buffer.as_mut_slice().iter_mut() {
            *value = z;
        }
    }

    /// Placeholder for returning a buffer (no-op for now, would be a pool in production).
    #[inline(always)]
    fn return_buffer(&self, _buf: B::Buffer) {
        // Buffer is dropped; could be returned to a pool for reuse
    }
}

struct ExactTeDownfoldingTerms {
    xi_scalar_first_order: Vec<Complex64>,
    kappa_matrices: [Vec<Complex64>; 2],
    weighted_leakage_scalar: Vec<Complex64>,
    lowdin_t_matrices: [Vec<Complex64>; 2],
    lowdin_r_matrix: Vec<Complex64>,
}
